const chicken = {
    chicken1: {
    "idMeal": "52795",
    "strMeal": "Chicken Handi",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "Indian",
    "strInstructions": "Take a large pot or wok, big enough to cook all the chicken, and heat the oil in it. Once the oil is hot, add sliced onion and fry them until deep golden brown. Then take them out on a plate and set aside.\r\nTo the same pot, add the chopped garlic and sauté for a minute. Then add the chopped tomatoes and cook until tomatoes turn soft. This would take about 5 minutes.\r\nThen return the fried onion to the pot and stir. Add ginger paste and sauté well.\r\nNow add the cumin seeds, half of the coriander seeds and chopped green chillies. Give them a quick stir.\r\nNext goes in the spices – turmeric powder and red chilli powder. Sauté the spices well for couple of minutes.\r\nAdd the chicken pieces to the wok, season it with salt to taste and cook the chicken covered on medium-low heat until the chicken is almost cooked through. This would take about 15 minutes. Slowly sautéing the chicken will enhance the flavor, so do not expedite this step by putting it on high heat.\r\nWhen the oil separates from the spices, add the beaten yogurt keeping the heat on lowest so that the yogurt doesn’t split. Sprinkle the remaining coriander seeds and add half of the dried fenugreek leaves. Mix well.\r\nFinally add the cream and give a final mix to combine everything well.\r\nSprinkle the remaining kasuri methi and garam masala and serve the chicken handi hot with naan or rotis. Enjoy!",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
    "strTags": null,
    "strYoutube": "https://www.youtube.com/watch?v=IO0issT0Rmc",
    "strIngredient1": "Chicken",
    "strIngredient2": "Onion",
    "strIngredient3": "Tomatoes",
    "strIngredient4": "Garlic",
    "strIngredient5": "Ginger paste",
    "strIngredient6": "Vegetable oil",
    "strIngredient7": "Cumin seeds",
    "strIngredient8": "Coriander seeds",
    "strIngredient9": "Turmeric powder",
    "strIngredient10": "Chilli powder",
    "strIngredient11": "Green chilli",
    "strIngredient12": "Yogurt",
    "strIngredient13": "Cream",
    "strIngredient14": "fenugreek",
    "strIngredient15": "Garam masala",
    "strIngredient16": "Salt",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "1.2 kg",
    "strMeasure2": "5 thinly sliced",
    "strMeasure3": "2 finely chopped",
    "strMeasure4": "8 cloves chopped",
    "strMeasure5": "1 tbsp",
    "strMeasure6": "¼ cup",
    "strMeasure7": "2 tsp",
    "strMeasure8": "3 tsp",
    "strMeasure9": "1 tsp",
    "strMeasure10": "1 tsp",
    "strMeasure11": "2",
    "strMeasure12": "1 cup",
    "strMeasure13": "¾ cup",
    "strMeasure14": "3 tsp Dried",
    "strMeasure15": "1 tsp",
    "strMeasure16": "To taste",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "",
    "dateModified": null
    },
    chicken2: {
    "idMeal": "52956",
    "strMeal": "Chicken Congee",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "Chinese",
    "strInstructions": "STEP 1 - MARINATING THE CHICKEN\r\nIn a bowl, add chicken, salt, white pepper, ginger juice and then mix it together well.\r\nSet the chicken aside.\r\nSTEP 2 - RINSE THE WHITE RICE\r\nRinse the rice in a metal bowl or pot a couple times and then drain the water.\r\nSTEP 2 - BOILING THE WHITE RICE\r\nNext add 8 cups of water and then set the stove on high heat until it is boiling. Once rice porridge starts to boil, set the stove on low heat and then stir it once every 8-10 minutes for around 20-25 minutes.\r\nAfter 25 minutes, this is optional but you can add a little bit more water to make rice porridge to make it less thick or to your preference.\r\nNext add the marinated chicken to the rice porridge and leave the stove on low heat for another 10 minutes.\r\nAfter an additional 10 minutes add the green onions, sliced ginger, 1 pinch of salt, 1 pinch of white pepper and stir for 10 seconds.\r\nServe the rice porridge in a bowl\r\nOptional: add Coriander on top of the rice porridge.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/1529446352.jpg",
    "strTags": null,
    "strYoutube": "https://www.youtube.com/watch?v=kqEfk801E94",
    "strIngredient1": "Chicken",
    "strIngredient2": "Salt",
    "strIngredient3": "Pepper",
    "strIngredient4": "Ginger Cordial",
    "strIngredient5": "Ginger",
    "strIngredient6": "Spring Onions",
    "strIngredient7": "Rice",
    "strIngredient8": "Water",
    "strIngredient9": "Coriander",
    "strIngredient10": "",
    "strIngredient11": "",
    "strIngredient12": "",
    "strIngredient13": "",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "8 oz ",
    "strMeasure2": "pinch",
    "strMeasure3": "pinch",
    "strMeasure4": "1 tsp ",
    "strMeasure5": "1 tsp ",
    "strMeasure6": "1 tbs",
    "strMeasure7": "1/2 cup ",
    "strMeasure8": "8 cups ",
    "strMeasure9": "2 oz ",
    "strMeasure10": "",
    "strMeasure11": "",
    "strMeasure12": "",
    "strMeasure13": "",
    "strMeasure14": "",
    "strMeasure15": "",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://sueandgambo.com/pages/chicken-congee",
    "dateModified": null
    },
    chicken3: {
    "idMeal": "52831",
    "strMeal": "Chicken Karaage",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "Japanese",
    "strInstructions": "Add the ginger, garlic, soy sauce, sake and sugar to a bowl and whisk to combine. Add the chicken, then stir to coat evenly. Cover and refrigerate for at least 1 hour.\r\n\r\nAdd 1 inch of vegetable oil to a heavy bottomed pot and heat until the oil reaches 360 degrees F. Line a wire rack with 2 sheets of paper towels and get your tongs out. Put the potato starch in a bowl\r\n\r\nAdd a handful of chicken to the potato starch and toss to coat each piece evenly.\r\n\r\nFry the karaage in batches until the exterior is a medium brown and the chicken is cooked through. Transfer the fried chicken to the paper towel lined rack. If you want the karaage to stay crispy longer, you can fry the chicken a second time, until it's a darker color after it's cooled off once. Serve with lemon wedges.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/tyywsw1505930373.jpg",
    "strTags": null,
    "strYoutube": "https://www.youtube.com/watch?v=XivddFddthc",
    "strIngredient1": "Chicken thigh",
    "strIngredient2": "Ginger",
    "strIngredient3": "Garlic",
    "strIngredient4": "Soy sauce",
    "strIngredient5": "Sake",
    "strIngredient6": "Granulated sugar",
    "strIngredient7": "Potato starch",
    "strIngredient8": "Vegetable oil",
    "strIngredient9": "Lemon",
    "strIngredient10": "",
    "strIngredient11": "",
    "strIngredient12": "",
    "strIngredient13": "",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "450 grams Boneless skin",
    "strMeasure2": "1 tablespoon",
    "strMeasure3": "1 clove",
    "strMeasure4": "2 tablespoons",
    "strMeasure5": "1 tablespoon",
    "strMeasure6": "2 teaspoon",
    "strMeasure7": "1/3 cup",
    "strMeasure8": "1/3 cup",
    "strMeasure9": "1/3 cup",
    "strMeasure10": "",
    "strMeasure11": "",
    "strMeasure12": "",
    "strMeasure13": "",
    "strMeasure14": "",
    "strMeasure15": "",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://norecipes.com/karaage-recipe",
    "dateModified": null
    },
    chicken4: {
    "idMeal": "52920",
    "strMeal": "Chicken Marengo",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "French",
    "strInstructions": "Heat the oil in a large flameproof casserole dish and stir-fry the mushrooms until they start to soften. Add the chicken legs and cook briefly on each side to colour them a little.\r\nPour in the passata, crumble in the stock cube and stir in the olives. Season with black pepper – you shouldn’t need salt. Cover and simmer for 40 mins until the chicken is tender. Sprinkle with parsley and serve with pasta and a salad, or mash and green veg, if you like.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qpxvuq1511798906.jpg",
    "strTags": null,
    "strYoutube": "https://www.youtube.com/watch?v=U33HYUr-0Fw",
    "strIngredient1": "Olive Oil",
    "strIngredient2": "Mushrooms",
    "strIngredient3": "Chicken Legs",
    "strIngredient4": "Passata",
    "strIngredient5": "Chicken Stock Cube",
    "strIngredient6": "Black Olives",
    "strIngredient7": "Parsley",
    "strIngredient8": "",
    "strIngredient9": "",
    "strIngredient10": "",
    "strIngredient11": "",
    "strIngredient12": "",
    "strIngredient13": "",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "1 tbs",
    "strMeasure2": "300g",
    "strMeasure3": "4",
    "strMeasure4": "500g",
    "strMeasure5": "1",
    "strMeasure6": "100g ",
    "strMeasure7": "Chopped",
    "strMeasure8": "",
    "strMeasure9": "",
    "strMeasure10": "",
    "strMeasure11": "",
    "strMeasure12": "",
    "strMeasure13": "",
    "strMeasure14": "",
    "strMeasure15": "",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://www.bbcgoodfood.com/recipes/3146682/chicken-marengo",
    "dateModified": null
    },
    chicken5: {
    "idMeal": "52806",
    "strMeal": "Tandoori chicken",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "Indian",
    "strInstructions": "Mix the lemon juice with the paprika and red onions in a large shallow dish. Slash each chicken thigh three times, then turn them in the juice and set aside for 10 mins.\r\nMix all of the marinade ingredients together and pour over the chicken. Give everything a good mix, then cover and chill for at least 1 hr. This can be done up to a day in advance.\r\nHeat the grill. Lift the chicken pieces onto a rack over a baking tray. Brush over a little oil and grill for 8 mins on each side or until lightly charred and completely cooked through.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg",
    "strTags": "Spicy,Meat",
    "strYoutube": "https://www.youtube.com/watch?v=-CKvt1KNU74",
    "strIngredient1": "lemons",
    "strIngredient2": "paprika",
    "strIngredient3": "red onions",
    "strIngredient4": "chicken thighs",
    "strIngredient5": "vegetable oil",
    "strIngredient6": "Greek yogurt",
    "strIngredient7": "ginger",
    "strIngredient8": "garlic clove",
    "strIngredient9": "garam masala",
    "strIngredient10": "ground cumin",
    "strIngredient11": "chilli powder",
    "strIngredient12": "turmeric",
    "strIngredient13": "",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "2 Juice",
    "strMeasure2": "4 tsp",
    "strMeasure3": "2 finely chopped",
    "strMeasure4": "16 skinnless",
    "strMeasure5": "For brushing",
    "strMeasure6": "300ml ",
    "strMeasure7": "large piece",
    "strMeasure8": "4",
    "strMeasure9": "¾ tsp",
    "strMeasure10": "¾ tsp",
    "strMeasure11": "½ tsp",
    "strMeasure12": "¼ tsp",
    "strMeasure13": "",
    "strMeasure14": "",
    "strMeasure15": "",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "http://www.bbcgoodfood.com/recipes/1660651/tandoori-chicken",
    "dateModified": null
    },
    chicken6: {
    "idMeal": "52850",
    "strMeal": "Chicken Couscous",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "Moroccan",
    "strInstructions": "Heat the olive oil in a large frying pan and cook the onion for 1-2 mins just until softened. Add the chicken and fry for 7-10 mins until cooked through and the onions have turned golden. Grate over the ginger, stir through the harissa to coat everything and cook for 1 min more.\r\n\r\nTip in the apricots, chickpeas and couscous, then pour over the stock and stir once. Cover with a lid or tightly cover the pan with foil and leave for about 5 mins until the couscous has soaked up all the stock and is soft. Fluff up the couscous with a fork and scatter over the coriander to serve. Serve with extra harissa, if you like.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/qxytrx1511304021.jpg",
    "strTags": null,
    "strYoutube": "https://www.youtube.com/watch?v=GZQGy9oscVk",
    "strIngredient1": "Olive Oil",
    "strIngredient2": "Onion",
    "strIngredient3": "Chicken Breast",
    "strIngredient4": "Ginger",
    "strIngredient5": "Harissa Spice",
    "strIngredient6": "Dried Apricots",
    "strIngredient7": "Chickpeas",
    "strIngredient8": "Couscous",
    "strIngredient9": "Chicken Stock",
    "strIngredient10": "Coriander",
    "strIngredient11": "",
    "strIngredient12": "",
    "strIngredient13": "",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "1 tbsp",
    "strMeasure2": "1 chopped",
    "strMeasure3": "200g",
    "strMeasure4": "pinch",
    "strMeasure5": "2 tblsp ",
    "strMeasure6": "10",
    "strMeasure7": "220g",
    "strMeasure8": "200g",
    "strMeasure9": "200ml",
    "strMeasure10": "Handful",
    "strMeasure11": "",
    "strMeasure12": "",
    "strMeasure13": "",
    "strMeasure14": "",
    "strMeasure15": "",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://www.bbcgoodfood.com/recipes/13139/onepan-chicken-couscous",
    "dateModified": null
    },
    chicken7: {
    "idMeal": "52945",
    "strMeal": "Kung Pao Chicken",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "Chinese",
    "strInstructions": "Combine the sake or rice wine, soy sauce, sesame oil and cornflour dissolved in water. Divide mixture in half.\r\nIn a glass dish or bowl, combine half of the sake mixture with the chicken pieces and toss to coat. Cover dish and place in refrigerator for about 30 minutes.\r\nIn a medium frying pan, combine remaining sake mixture, chillies, vinegar and sugar. Mix together and add spring onion, garlic, water chestnuts and peanuts. Heat sauce slowly over medium heat until aromatic.\r\nMeanwhile, remove chicken from marinade and sauté in a large frying pan until juices run clear. When sauce is aromatic, add sautéed chicken and let simmer together until sauce thickens.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/1525872624.jpg",
    "strTags": null,
    "strYoutube": "https://www.youtube.com/watch?v=QqdcCHQlOe0",
    "strIngredient1": "Sake",
    "strIngredient2": "Soy Sauce",
    "strIngredient3": "Sesame Seed Oil",
    "strIngredient4": "Corn Flour",
    "strIngredient5": "Water",
    "strIngredient6": "Chicken",
    "strIngredient7": "Chilli Powder",
    "strIngredient8": "Rice Vinegar",
    "strIngredient9": "Brown Sugar",
    "strIngredient10": "Spring Onions",
    "strIngredient11": "Garlic Clove",
    "strIngredient12": "Water Chestnut",
    "strIngredient13": "Peanuts",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "2 tbs",
    "strMeasure2": "2 tbs",
    "strMeasure3": "2 tbs",
    "strMeasure4": "2 tbs",
    "strMeasure5": "2 tbs",
    "strMeasure6": "500g",
    "strMeasure7": "1 tbs",
    "strMeasure8": "1 tsp ",
    "strMeasure9": "1 tbs",
    "strMeasure10": "4 Chopped",
    "strMeasure11": "6 cloves",
    "strMeasure12": "220g",
    "strMeasure13": "100g ",
    "strMeasure14": "",
    "strMeasure15": "",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "http://allrecipes.co.uk/recipe/1773/kung-pao-chicken.aspx",
    "dateModified": null
    },
    chicken8: {
    "idMeal": "52934",
    "strMeal": "Chicken Basquaise",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "French",
    "strInstructions": "Preheat the oven to 180°C/Gas mark 4. Have the chicken joints ready to cook. Heat the butter and 3 tbsp olive oil in a flameproof casserole or large frying pan. Brown the chicken pieces in batches on both sides, seasoning them with salt and pepper as you go. Don't crowd the pan - fry the chicken in small batches, removing the pieces to kitchen paper as they are done.\r\n\r\nAdd a little more olive oil to the casserole and fry the onions over a medium heat for 10 minutes, stirring frequently, until softened but not browned. Add the rest of the oil, then the peppers and cook for another 5 minutes.\r\n\r\nAdd the chorizo, sun-dried tomatoes and garlic and cook for 2-3 minutes. Add the rice, stirring to ensure it is well coated in the oil. Stir in the tomato paste, paprika, bay leaves and chopped thyme. Pour in the stock and wine. When the liquid starts to bubble, turn the heat down to a gentle simmer. Press the rice down into the liquid if it isn't already submerged and place the chicken on top. Add the lemon wedges and olives around the chicken.\r\n\r\nCover and cook in the oven for 50 minutes. The rice should be cooked but still have some bite, and the chicken should have juices that run clear when pierced in the thickest part with a knife. If not, cook for another 5 minutes and check again.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/wruvqv1511880994.jpg",
    "strTags": "Meat",
    "strYoutube": "https://www.youtube.com/watch?v=emfm6TwsVhg",
    "strIngredient1": "Chicken",
    "strIngredient2": "Butter",
    "strIngredient3": "Olive Oil",
    "strIngredient4": "Red Onions",
    "strIngredient5": "Red Pepper",
    "strIngredient6": "Chorizo",
    "strIngredient7": "Sun-Dried Tomatoes",
    "strIngredient8": "Garlic",
    "strIngredient9": "Basmati Rice",
    "strIngredient10": "Tomato Puree",
    "strIngredient11": "Paprika",
    "strIngredient12": "Bay Leaves",
    "strIngredient13": "Thyme",
    "strIngredient14": "Chicken Stock",
    "strIngredient15": "Dry White Wine",
    "strIngredient16": "Lemons",
    "strIngredient17": "Black Olives",
    "strIngredient18": "Salt",
    "strIngredient19": "Pepper",
    "strIngredient20": "",
    "strMeasure1": "1.5kg",
    "strMeasure2": "25g",
    "strMeasure3": "6 tblsp",
    "strMeasure4": "2 sliced",
    "strMeasure5": "3 Large",
    "strMeasure6": "130g",
    "strMeasure7": "8",
    "strMeasure8": "6 cloves sliced",
    "strMeasure9": "300g",
    "strMeasure10": "drizzle",
    "strMeasure11": "½ tsp",
    "strMeasure12": "4",
    "strMeasure13": "Handful",
    "strMeasure14": "350ml",
    "strMeasure15": "180g",
    "strMeasure16": "2",
    "strMeasure17": "100g ",
    "strMeasure18": "to serve",
    "strMeasure19": "to serve",
    "strMeasure20": "",
    "strSource": "https://www.rivercottage.net/recipes/chicken-basquaise",
    "dateModified": null
    },
    chicken9: {
    "idMeal": "52879",
    "strMeal": "Chicken Parmentier",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "French",
    "strInstructions": "For the topping, boil the potatoes in salted water until tender. Drain and push through a potato ricer, or mash thoroughly. Stir in the butter, cream and egg yolks. Season and set aside.\r\nFor the filling, melt the butter in a large pan. Add the shallots, carrots and celery and gently fry until soft, then add the garlic. Pour in the wine and cook for 1 minute. Stir in the tomato purée, chopped tomatoes and stock and cook for 10–15 minutes, until thickened. Add the shredded chicken, olives and parsley. Season to taste with salt and pepper.\r\nPreheat the oven to 180C/160C Fan/Gas 4.\r\nPut the filling in a 20x30cm/8x12in ovenproof dish and top with the mashed potato. Grate over the Gruyère. Bake for 30–35 minutes, until piping hot and the potato is golden-brown.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/uwvxpv1511557015.jpg",
    "strTags": "Meat,Dairy",
    "strYoutube": "https://www.youtube.com/watch?v=tiG-xlmeyjg",
    "strIngredient1": "Potatoes",
    "strIngredient2": "Butter",
    "strIngredient3": "Double Cream",
    "strIngredient4": "Egg Yolks",
    "strIngredient5": "Butter",
    "strIngredient6": "Shallots",
    "strIngredient7": "Carrots",
    "strIngredient8": "Celery",
    "strIngredient9": "Garlic Clove",
    "strIngredient10": "White Wine",
    "strIngredient11": "Tomato Puree",
    "strIngredient12": "Tinned Tomatos",
    "strIngredient13": "Chicken Stock",
    "strIngredient14": "Chicken",
    "strIngredient15": "Black Olives",
    "strIngredient16": "Parsley",
    "strIngredient17": "Gruyere cheese",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "1.5kg",
    "strMeasure2": "30g",
    "strMeasure3": "5 tblsp ",
    "strMeasure4": "2",
    "strMeasure5": "30g",
    "strMeasure6": "7",
    "strMeasure7": "3 chopped",
    "strMeasure8": "2 sticks",
    "strMeasure9": "1 finely chopped ",
    "strMeasure10": "4 tbsp",
    "strMeasure11": "1 tbls",
    "strMeasure12": "400g",
    "strMeasure13": "350ml",
    "strMeasure14": "600g",
    "strMeasure15": "16",
    "strMeasure16": "2 tbs",
    "strMeasure17": "50g",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://www.bbc.co.uk/food/recipes/chicken_parmentier_25434",
    "dateModified": null
    },
    chicken10: {
    "idMeal": "52940",
    "strMeal": "Brown Stew Chicken",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "Jamaican",
    "strInstructions": "Squeeze lime over chicken and rub well. Drain off excess lime juice.\r\nCombine tomato, scallion, onion, garlic, pepper, thyme, pimento and soy sauce in a large bowl with the chicken pieces. Cover and marinate at least one hour.\r\nHeat oil in a dutch pot or large saucepan. Shake off the seasonings as you remove each piece of chicken from the marinade. Reserve the marinade for sauce.\r\nLightly brown the chicken a few pieces at a time in very hot oil. Place browned chicken pieces on a plate to rest while you brown the remaining pieces.\r\nDrain off excess oil and return the chicken to the pan. Pour the marinade over the chicken and add the carrots. Stir and cook over medium heat for 10 minutes.\r\nMix flour and coconut milk and add to stew, stirring constantly. Turn heat down to minimum and cook another 20 minutes or until tender.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg",
    "strTags": "Stew",
    "strYoutube": "https://www.youtube.com/watch?v=_gFB1fkNhXs",
    "strIngredient1": "Chicken",
    "strIngredient2": "Tomato",
    "strIngredient3": "Onions",
    "strIngredient4": "Garlic Clove",
    "strIngredient5": "Red Pepper",
    "strIngredient6": "Carrots",
    "strIngredient7": "Lime",
    "strIngredient8": "Thyme",
    "strIngredient9": "Allspice",
    "strIngredient10": "Soy Sauce",
    "strIngredient11": "Cornstarch",
    "strIngredient12": "Coconut Milk",
    "strIngredient13": "Vegetable Oil",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "1 whole",
    "strMeasure2": "1 chopped",
    "strMeasure3": "2 chopped",
    "strMeasure4": "2 chopped",
    "strMeasure5": "1 chopped",
    "strMeasure6": "1 chopped",
    "strMeasure7": "1",
    "strMeasure8": "2 tsp",
    "strMeasure9": "1 tsp ",
    "strMeasure10": "2 tbs",
    "strMeasure11": "2 tsp",
    "strMeasure12": "2 cups ",
    "strMeasure13": "1 tbs",
    "strMeasure14": "",
    "strMeasure15": "",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "http://www.geniuskitchen.com/recipe/authentic-jamaican-brown-stew-chicken-347996",
    "dateModified": null
    },
    chicken11: {
    "idMeal": "52820",
    "strMeal": "Katsu Chicken curry",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "Japanese",
    "strInstructions": "Prep:15min  ›  Cook:30min  ›  Ready in:45min \r\n\r\nFor the curry sauce: Heat oil in medium non-stick saucepan, add onion and garlic and cook until softened. Stir in carrots and cook over low heat for 10 to 12 minutes.\r\nAdd flour and curry powder; cook for 1 minute. Gradually stir in stock until combined; add honey, soy sauce and bay leaf. Slowly bring to the boil.\r\nTurn down heat and simmer for 20 minutes or until sauce thickens but is still of pouring consistency. Stir in garam masala. Pour the curry sauce through a sieve; return to saucepan and keep on low heat until ready to serve.\r\nFor the chicken: Season both sides of chicken breasts with salt and pepper. Place flour, egg and breadcrumbs in separate bowls and arrange in a row. Coat the chicken breasts in flour, then dip them into the egg, then coat in breadcrumbs, making sure you cover both sides.\r\nHeat oil in large frying pan over medium-high heat. Place chicken into hot oil and cook until golden brown, about 3 or 4 minutes each side. Once cooked, place on kitchen paper to absorb excess oil.\r\nPour curry sauce over chicken, serve with white rice and enjoy!",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg",
    "strTags": "Curry,Meat",
    "strYoutube": "https://www.youtube.com/watch?v=MWzxDFRtVbc",
    "strIngredient1": "chicken breast",
    "strIngredient2": "plain flour",
    "strIngredient3": "egg",
    "strIngredient4": "breadcrumbs",
    "strIngredient5": "vegetable oil",
    "strIngredient6": "sunflower oil",
    "strIngredient7": "onions",
    "strIngredient8": "garlic",
    "strIngredient9": "carrot",
    "strIngredient10": "plain flour",
    "strIngredient11": "curry powder",
    "strIngredient12": "chicken stock",
    "strIngredient13": "honey",
    "strIngredient14": "soy sauce",
    "strIngredient15": "bay leaf",
    "strIngredient16": "garam masala",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "4 pounded to 1cm thickness",
    "strMeasure2": "2 tablespoons",
    "strMeasure3": "1 beaten",
    "strMeasure4": "100g fine",
    "strMeasure5": "230ml frying",
    "strMeasure6": "2 tablespoons",
    "strMeasure7": "2 sliced",
    "strMeasure8": "5 chopped cloves",
    "strMeasure9": "2 sliced",
    "strMeasure10": "2 tablespoons",
    "strMeasure11": "4 teaspoons",
    "strMeasure12": "600ml",
    "strMeasure13": "2 teaspoons",
    "strMeasure14": "4 teaspoons",
    "strMeasure15": "1",
    "strMeasure16": "1 teaspoon",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "http://allrecipes.co.uk/recipe/29578/chicken-katsu-curry.aspx",
    "dateModified": null
    },
    chicken12: {
    "idMeal": "52851",
    "strMeal": "Nutty Chicken Curry",
    "strDrinkAlternate": null,
    "strCategory": "Chicken",
    "strArea": "Indian",
    "strInstructions": "Finely slice a quarter of the chilli, then put the rest in a food processor with the ginger, garlic, coriander stalks and one-third of the leaves. Whizz to a rough paste with a splash of water if needed.\r\nHeat the oil in a frying pan, then quickly brown the chicken chunks for 1 min. Stir in the paste for another min, then add the peanut butter, stock and yogurt. When the sauce is gently bubbling, cook for 10 mins until the chicken is just cooked through and sauce thickened. Stir in most of the remaining coriander, then scatter the rest on top with the chilli, if using. Eat with rice or mashed sweet potato.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/yxsurp1511304301.jpg",
    "strTags": null,
    "strYoutube": "https://www.youtube.com/watch?v=nSQNfZxOdeU",
    "strIngredient1": "Red Chilli",
    "strIngredient2": "Ginger",
    "strIngredient3": "Garlic",
    "strIngredient4": "Coriander",
    "strIngredient5": "Sunflower Oil",
    "strIngredient6": "Chicken Breasts",
    "strIngredient7": "Peanut Butter",
    "strIngredient8": "Chicken Stock",
    "strIngredient9": "Greek Yogurt",
    "strIngredient10": "",
    "strIngredient11": "",
    "strIngredient12": "",
    "strIngredient13": "",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "1 large",
    "strMeasure2": "0.5",
    "strMeasure3": "1 large",
    "strMeasure4": "Bunch",
    "strMeasure5": "1 tbsp",
    "strMeasure6": "4",
    "strMeasure7": "5 tblsp ",
    "strMeasure8": "150ml",
    "strMeasure9": "200g",
    "strMeasure10": "",
    "strMeasure11": "",
    "strMeasure12": "",
    "strMeasure13": "",
    "strMeasure14": "",
    "strMeasure15": "",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://www.bbcgoodfood.com/recipes/11753/nutty-chicken-curry",
    "dateModified": null
    },
    
}

export default chicken;