const dessert = {
    dessert1: {
        "idMeal": "52901",
        "strMeal": "Rock Cakes",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "Preheat oven to 180C/350F/Gas 4 and line a baking tray with baking parchment.\r\nMix the flour, sugar and baking powder in a bowl and rub in the cubed butter until the mixture looks like breadcrumbs, then mix in the dried fruit.\r\nIn a clean bowl, beat the egg and milk together with the vanilla extract.\r\nAdd the egg mixture to the dry ingredients and stir with a spoon until the mixture just comes together as a thick, lumpy dough. Add a teaspoon more milk if you really need it to make the mixture stick together.\r\nPlace golfball-sized spoons of the mixture onto the prepared baking tray. Leave space between them as they will flatten and spread out to double their size during baking.\r\nBake for 15-20 minutes, until golden-brown. Remove from the oven, allow to cool for a couple of minutes then turn them out onto a wire rack to cool.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/tqrrsq1511723764.jpg",
        "strTags": "Baking,Cake",
        "strYoutube": "https://www.youtube.com/watch?v=tY3taZO3Aro",
        "strIngredient1": "Self-raising Flour",
        "strIngredient2": "Caster Sugar",
        "strIngredient3": "Baking Powder",
        "strIngredient4": "Butter",
        "strIngredient5": "Dried Fruit",
        "strIngredient6": "Eggs",
        "strIngredient7": "Milk",
        "strIngredient8": "Vanilla Extract",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "225g",
        "strMeasure2": "75g",
        "strMeasure3": "1 tsp ",
        "strMeasure4": "125g",
        "strMeasure5": "150g",
        "strMeasure6": "1",
        "strMeasure7": "1 tbs",
        "strMeasure8": "2 tsp",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbc.co.uk/food/recipes/rock_cakes_03094",
        "dateModified": null
        },
        dessert2: {
        "idMeal": "52897",
        "strMeal": "Carrot Cake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "For the carrot cake, preheat the oven to 160C/325F/Gas 3. Grease and line a 26cm/10in springform cake tin.\r\nMix all of the ingredients for the carrot cake, except the carrots and walnuts, together in a bowl until well combined. Stir in the carrots and walnuts.\r\nSpoon the mixture into the cake tin and bake for 1 hour 15 minutes, or until a skewer inserted into the middle comes out clean. Remove the cake from the oven and set aside to cool for 10 minutes, then carefully remove the cake from the tin and set aside to cool completely on a cooling rack.\r\nMeanwhile, for the icing, beat the cream cheese, caster sugar and butter together in a bowl until fluffy. Spread the icing over the top of the cake with a palette knife.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/vrspxv1511722107.jpg",
        "strTags": "Cake,Treat,Sweet",
        "strYoutube": "https://www.youtube.com/watch?v=asjZ7iTrGKA",
        "strIngredient1": "Vegetable Oil",
        "strIngredient2": "Plain Flour",
        "strIngredient3": "Bicarbonate Of Soda",
        "strIngredient4": "Sugar",
        "strIngredient5": "Eggs",
        "strIngredient6": "Salt",
        "strIngredient7": "Cinnamon",
        "strIngredient8": "Carrots",
        "strIngredient9": "Walnuts",
        "strIngredient10": "Cream Cheese",
        "strIngredient11": "Caster Sugar",
        "strIngredient12": "Butter",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "450ml",
        "strMeasure2": "400g",
        "strMeasure3": "2 tsp",
        "strMeasure4": "550ml",
        "strMeasure5": "5",
        "strMeasure6": "½ tsp",
        "strMeasure7": "2 tsp",
        "strMeasure8": "500g grated",
        "strMeasure9": "150g",
        "strMeasure10": "200g",
        "strMeasure11": "150g",
        "strMeasure12": "100g ",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbc.co.uk/food/recipes/classic_carrot_cake_08513",
        "dateModified": null
        },
        dessert3: {
        "idMeal": "52899",
        "strMeal": "Dundee cake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "Put the almonds into a small bowl and pour over boiling water to just cover. Leave for 5 mins then drain in a sieve and leave to dry.\r\nPreheat the oven to 180C/160 C fan/Gas Mark 4. Line a deep loose-based 20cm cake tin with baking parchment.\r\nPut the butter in a large bowl and beat well until soft. Add the sugar and beat until light and fluffy. Stir in the orange zest and apricot jam.\r\nSieve together the flour and baking powder. Add the eggs to the creamed butter and sugar, a little at a time, beating well between each addition. If the mixture starts to curdle, stir in a little flour.\r\nAdd the remaining flour and ground almonds and mix well. Mix in the milk and then add the dried fruit and cherries and mix gently together.\r\nSpoon the mixture into the prepared tin and spread level using the back of a spoon. Arrange the whole almonds close together in neat circles on the top of the cake. Bake in the oven for 45 mins.\r\nLower the oven temperature to 160C/140 C fan/Gas Mark 3 and cook for a further 60–80 minutes. Check the cake after 50 minutes by inserting a wooden or metal skewer into the cake. When it’s done it should have just a few crumbs attached. Check every 10 minutes - it’s important not to overcook this cake so the centre will be a little soft.\r\nWhen cooked, remove the cake briefly from the oven, put the milk and sugar into a small pan and heat gently until the sugar has dissolved. Brush over the top of the cake and return the cake to the oven for 2-3 mins. Remove and allow the cake to cool in the tin. When quite cold remove from the tin and wrap in foil and keep for at least 2 days before cutting.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/wxyvqq1511723401.jpg",
        "strTags": "heavy,Nutty,Fruity",
        "strYoutube": "https://www.youtube.com/watch?v=4hEXsfpeMQE",
        "strIngredient1": "Almonds",
        "strIngredient2": "Butter",
        "strIngredient3": "Muscovado Sugar",
        "strIngredient4": "Orange",
        "strIngredient5": "Apricot Jam",
        "strIngredient6": "Plain Flour",
        "strIngredient7": "Baking Powder",
        "strIngredient8": "Eggs",
        "strIngredient9": "Ground Almonds",
        "strIngredient10": "Milk",
        "strIngredient11": "Dried Fruit",
        "strIngredient12": "Glace Cherry",
        "strIngredient13": "Milk",
        "strIngredient14": "Caster Sugar",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "100g ",
        "strMeasure2": "180g",
        "strMeasure3": "180g",
        "strMeasure4": "Zest of 1",
        "strMeasure5": "3 tbs",
        "strMeasure6": "225g",
        "strMeasure7": "1 tsp ",
        "strMeasure8": "3 Large",
        "strMeasure9": "100g ",
        "strMeasure10": "2 tbs",
        "strMeasure11": "500g",
        "strMeasure12": "100g ",
        "strMeasure13": "1 tbs",
        "strMeasure14": "2 tsp",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/2155640/dundee-cake",
        "dateModified": null
        },
        dessert4: {
        "idMeal": "52902",
        "strMeal": "Parkin Cake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "Heat oven to 160C/140C fan/gas 3. Grease a deep 22cm/9in square cake tin and line with baking parchment. Beat the egg and milk together with a fork.\r\n\r\nGently melt the syrup, treacle, sugar and butter together in a large pan until the sugar has dissolved. Remove from the heat. Mix together the oatmeal, flour and ginger and stir into the syrup mixture, followed by the egg and milk.\r\n\r\nPour the mixture into the tin and bake for 50 mins - 1 hr until the cake feels firm and a little crusty on top. Cool in the tin then wrap in more parchment and foil and keep for 3-5 days before eating if you can – it’ll become softer and stickier the longer you leave it, up to 2 weeks.\r\n",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/qxuqtt1511724269.jpg",
        "strTags": "Caramel",
        "strYoutube": "https://www.youtube.com/watch?v=k1lG4vk2MQA",
        "strIngredient1": "Butter",
        "strIngredient2": "Egg",
        "strIngredient3": "Milk",
        "strIngredient4": "Golden Syrup",
        "strIngredient5": "Black Treacle",
        "strIngredient6": "Brown Sugar",
        "strIngredient7": "Oatmeal",
        "strIngredient8": "Self-raising Flour",
        "strIngredient9": "Ground Ginger",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "200g",
        "strMeasure2": "1 large",
        "strMeasure3": "4 tbs",
        "strMeasure4": "200g",
        "strMeasure5": "85g",
        "strMeasure6": "85g",
        "strMeasure7": "100g ",
        "strMeasure8": "250g",
        "strMeasure9": "1 tbs",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/1940684/parkin",
        "dateModified": null
        },
        dessert5: {
        "idMeal": "52888",
        "strMeal": "Eccles Cakes",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "To make the pastry, dice the butter and put it in the freezer to go really hard. Tip flour into the bowl of a food processor with half the butter and pulse to the texture of breadcrumbs. Pour in the lemon juice and 100ml iced water, and pulse to a dough. Tip in the rest of the butter and pulse a few times until the dough is heavily flecked with butter. It is important that you don’t overdo this as the flecks of butter are what makes the pastry flaky.\r\nOn a floured surface roll the pastry out to a neat rectangle about 20 x 30cm. Fold the two ends of the pastry into the middle (See picture 1), then fold in half (pic 2). Roll the pastry out again and refold the same way 3 more times resting the pastry for at least 15 mins each time between roll and fold, then leave to rest in the fridge for at least 30 mins before using.\r\nTo make the filling, melt the butter in a large saucepan. Take it off the heat and stir in all the other ingredients until completely mixed, then set aside.\r\nTo make the cakes, roll the pastry out until it’s just a little thicker than a £1 coin and cut out 8 rounds about 12cm across. Re-roll the trimming if needed. Place a good heaped tablespoon of mixture in the middle of each round, brush the edges of the rounds with water, then gather the pastry around the filling and squeeze it together (pic 3). Flip them over so the smooth top is upwards and pat them into a smooth round. Flatten each round with a rolling pin to an oval until the fruit just starts to poke through, then place on a baking tray. Cut 2 little slits in each Eccles cakes, brush generously with egg white and sprinkle with the sugar (pic 4).\r\nHeat the oven to 220C/200C fan/gas 8. Bake the Eccles cakes for 15-20 mins until just past golden brown and sticky. Leave to cool on a rack and enjoy while still warm or cold with a cup of tea. If you prefer, Eccles cakes also go really well served with a wedge of hard, tangy British cheese such as Lancashire or cheddar.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/wtqrqw1511639627.jpg",
        "strTags": "Snack,Treat",
        "strYoutube": "https://www.youtube.com/watch?v=xV0QCJ0GD5w",
        "strIngredient1": "Butter",
        "strIngredient2": "Plain Flour",
        "strIngredient3": "Lemon",
        "strIngredient4": "Butter",
        "strIngredient5": "Currants",
        "strIngredient6": "Mixed Peel",
        "strIngredient7": "Muscovado Sugar",
        "strIngredient8": "Cinnamon",
        "strIngredient9": "Ginger",
        "strIngredient10": "Allspice",
        "strIngredient11": "Lemon",
        "strIngredient12": "Eggs",
        "strIngredient13": "Sugar",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "250g",
        "strMeasure2": "350g",
        "strMeasure3": "Juice of 1/2",
        "strMeasure4": "25g",
        "strMeasure5": "200g",
        "strMeasure6": "50g",
        "strMeasure7": "100g ",
        "strMeasure8": "1 tsp ",
        "strMeasure9": "1 tsp ",
        "strMeasure10": "1 tsp ",
        "strMeasure11": "Zest of 1",
        "strMeasure12": "1 beaten",
        "strMeasure13": "spinkling",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/786659/eccles-cakes",
        "dateModified": null
        },
        dessert6: {
        "idMeal": "52900",
        "strMeal": "Madeira Cake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "Pre-heat the oven to 180C/350F/Gas 4. Grease an 18cm/7in round cake tin, line the base with greaseproof paper and grease the paper.\r\nCream the butter and sugar together in a bowl until pale and fluffy. Beat in the eggs, one at a time, beating the mixture well between each one and adding a tablespoon of the flour with the last egg to prevent the mixture curdling.\r\nSift the flour and gently fold in, with enough milk to give a mixture that falls slowly from the spoon. Fold in the lemon zest.\r\nSpoon the mixture into the prepared tin and lightly level the top. Bake on the middle shelf of the oven for 30-40 minutes, or until golden-brown on top and a skewer inserted into the centre comes out clean.\r\nRemove from the oven and set aside to cool in the tin for 10 minutes, then turn it out on to a wire rack and leave to cool completely.\r\nTo serve, decorate the cake with the candied peel.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/urtqut1511723591.jpg",
        "strTags": "Cake,Light,Baking,Desert",
        "strYoutube": "https://www.youtube.com/watch?v=-YDh4WEmK_E",
        "strIngredient1": "Butter",
        "strIngredient2": "Caster Sugar",
        "strIngredient3": "Eggs",
        "strIngredient4": "Self-raising Flour",
        "strIngredient5": "Milk",
        "strIngredient6": "Lemon",
        "strIngredient7": "Mixed Peel",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "175g",
        "strMeasure2": "175g",
        "strMeasure3": "3",
        "strMeasure4": "250g",
        "strMeasure5": "3 tbs",
        "strMeasure6": "Zest of 1",
        "strMeasure7": "To Glaze",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbc.co.uk/food/recipes/madeiracake_73878",
        "dateModified": null
        },
        dessert7: {
        "idMeal": "52990",
        "strMeal": "Christmas cake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "Heat oven to 160C/fan 140C/gas 3. Line the base and sides of a 20 cm round, 7.5 cm deep cake tin. Beat the butter and sugar with an electric hand mixer for 1-2 mins until very creamy and pale in colour, scraping down the sides of the bowl half way through. Stir in a spoonful of the flour, then stir in the beaten egg and the rest of the flour alternately, a quarter at a time, beating well each time with a wooden spoon. Stir in the almonds.\r\n\r\nMix in the sherry (the mix will look curdled), then add the peel, cherries, raisins, cherries, nuts, lemon zest, spice, rosewater and vanilla. Beat together to mix, then stir in the baking powder.\r\n\r\nSpoon mixture into the tin and smooth the top, making a slight dip in the centre. Bake for 30 mins, then lower temperature to 150C/fan 130C/gas 2 and bake a further 2-2¼ hrs, until a skewer insterted in the middle comes out clean. Leave to cool in the tin, then take out of the tin and peel off the lining paper. When completely cold, wrap well in cling film and foil to store until ready to decorate. The cake will keep for several months.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/ldnrm91576791881.jpg",
        "strTags": "Christmas",
        "strYoutube": "https://www.youtube.com/watch?v=34yeL8TstO0",
        "strIngredient1": "Butter",
        "strIngredient2": "Muscovado Sugar",
        "strIngredient3": "Plain Flour",
        "strIngredient4": "Eggs",
        "strIngredient5": "Ground Almonds",
        "strIngredient6": "Sherry",
        "strIngredient7": "Candied Peel",
        "strIngredient8": "Glace Cherry",
        "strIngredient9": "Raisins",
        "strIngredient10": "Currants",
        "strIngredient11": "Pecan Nuts",
        "strIngredient12": "Lemon",
        "strIngredient13": "Mixed Spice",
        "strIngredient14": "Rose water",
        "strIngredient15": "Vanilla Extract",
        "strIngredient16": "Baking Powder",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "200g",
        "strMeasure2": "200g",
        "strMeasure3": "200g",
        "strMeasure4": "4 Beaten",
        "strMeasure5": "50g",
        "strMeasure6": "100ml",
        "strMeasure7": "85g",
        "strMeasure8": "85g",
        "strMeasure9": "250g",
        "strMeasure10": "250g",
        "strMeasure11": "100g ",
        "strMeasure12": "Grated zest of 1",
        "strMeasure13": "1 ½ tbsp",
        "strMeasure14": "1 ½ tbsp",
        "strMeasure15": "1/2 tsp",
        "strMeasure16": "1/2 tsp",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "https://www.bbcgoodfood.com/recipes/angela-nilsens-christmas-cake",
        "dateModified": null
        },
        dessert8: {
            "idMeal": "52894",
            "strMeal": "Battenberg Cake",
            "strDrinkAlternate": null,
            "strCategory": "Dessert",
            "strArea": "British",
            "strInstructions": "Heat oven to 180C/160C fan/gas 4 and line the base and sides of a 20cm square tin with baking parchment (the easiest way is to cross 2 x 20cm-long strips over the base). To make the almond sponge, put the butter, sugar, flour, ground almonds, baking powder, eggs, vanilla and almond extract in a large bowl. Beat with an electric whisk until the mix comes together smoothly. Scrape into the tin, spreading to the corners, and bake for 25-30 mins – when you poke in a skewer, it should come out clean. Cool in the tin for 10 mins, then transfer to a wire rack to finish cooling while you make the second sponge.\r\nFor the pink sponge, line the tin as above. Mix all the ingredients together as above, but don’t add the almond extract. Fold in some pink food colouring. Then scrape it all into the tin and bake as before. Cool.\r\nTo assemble, heat the jam in a small pan until runny, then sieve. Barely trim two opposite edges from the almond sponge, then well trim a third edge. Roughly measure the height of the sponge, then cutting from the well-trimmed edge, use a ruler to help you cut 4 slices each the same width as the sponge height. Discard or nibble leftover sponge. Repeat with pink cake.\r\nTake 2 x almond slices and 2 x pink slices and trim so they are all the same length. Roll out one marzipan block on a surface lightly dusted with icing sugar to just over 20cm wide, then keep rolling lengthways until the marzipan is roughly 0.5cm thick. Brush with apricot jam, then lay a pink and an almond slice side by side at one end of the marzipan, brushing jam in between to stick sponges, and leaving 4cm clear marzipan at the end. Brush more jam on top of the sponges, then sandwich remaining 2 slices on top, alternating colours to give a checkerboard effect. Trim the marzipan to the length of the cakes.\r\nCarefully lift up the marzipan and smooth over the cake with your hands, but leave a small marzipan fold along the bottom edge before you stick it to the first side. Trim opposite side to match size of fold, then crimp edges using fingers and thumb (or, more simply, press with prongs of fork). If you like, mark the 10 slices using the prongs of a fork.\r\nAssemble second Battenberg and keep in an airtight box or well wrapped in cling film for up to 3 days. Can be frozen for up to a month.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/ywwrsp1511720277.jpg",
            "strTags": "Cake,Sweet",
            "strYoutube": "https://www.youtube.com/watch?v=aB41Q7kDZQ0",
            "strIngredient1": "Butter",
            "strIngredient2": "Caster Sugar",
            "strIngredient3": "Self-raising Flour",
            "strIngredient4": "Almonds",
            "strIngredient5": "Baking Powder",
            "strIngredient6": "Eggs",
            "strIngredient7": "Vanilla Extract",
            "strIngredient8": "Almond Extract",
            "strIngredient9": "Butter",
            "strIngredient10": "Caster Sugar",
            "strIngredient11": "Self-raising Flour",
            "strIngredient12": "Almonds",
            "strIngredient13": "Baking Powder",
            "strIngredient14": "Eggs",
            "strIngredient15": "Vanilla Extract",
            "strIngredient16": "Almond Extract",
            "strIngredient17": "Pink Food Colouring",
            "strIngredient18": "Apricot",
            "strIngredient19": "Marzipan",
            "strIngredient20": "Icing Sugar",
            "strMeasure1": "175g",
            "strMeasure2": "175g",
            "strMeasure3": "140g",
            "strMeasure4": "50g",
            "strMeasure5": "½ tsp",
            "strMeasure6": "3 Medium",
            "strMeasure7": "½ tsp",
            "strMeasure8": "¼ teaspoon",
            "strMeasure9": "175g",
            "strMeasure10": "175g",
            "strMeasure11": "140g",
            "strMeasure12": "50g",
            "strMeasure13": "½ tsp",
            "strMeasure14": "3 Medium",
            "strMeasure15": "½ tsp",
            "strMeasure16": "¼ teaspoon",
            "strMeasure17": "½ tsp",
            "strMeasure18": "200g",
            "strMeasure19": "1kg",
            "strMeasure20": "Dusting",
            "strSource": "https://www.bbcgoodfood.com/recipes/1120657/battenberg-cake",
            "dateModified": null
            },
            dessert9: {
            "idMeal": "52858",
            "strMeal": "New York cheesecake",
            "strDrinkAlternate": null,
            "strCategory": "Dessert",
            "strArea": "American",
            "strInstructions": "Position an oven shelf in the middle of the oven. Preheat the oven to fan 160C/conventional 180C/gas 4. Line the base of a 23cm springform cake tin with parchment paper. For the crust, melt the butter in a medium pan. Stir in the biscuit crumbs and sugar so the mixture is evenly moistened. Press the mixture into the bottom of the pan and bake for 10 minutes. Cool on a wire rack while preparing the filling.\r\nFor the filling, increase the oven temperature to fan 200C/conventional 240C/gas 9. In a table top mixer fitted with the paddle attachment, beat the soft cheese at medium-low speed until creamy, about 2 minutes. With the mixer on low, gradually add the sugar, then the flour and a pinch of salt, scraping down the sides of the bowl and the paddle twice.\r\nSwap the paddle attachment for the whisk. Continue by adding the vanilla, lemon zest and juice. Whisk in the eggs and yolk, one at a time, scraping the bowl and whisk at least twice. Stir the 284ml carton of soured cream until smooth, then measure 200ml/7fl oz (just over 3⁄4 of the carton). Continue on low speed as you add the measured soured cream (reserve the rest). Whisk to blend, but don't over-beat. The batter should be smooth, light and somewhat airy.\r\nBrush the sides of the springform tin with melted butter and put on a baking sheet. Pour in the filling - if there are any lumps, sink them using a knife - the top should be as smooth as possible. Bake for 10 minutes. Reduce oven temperature to fan 90C/conventional 110C/gas 1⁄4 and bake for 25 minutes more. If you gently shake the tin, the filling should have a slight wobble. Turn off the oven and open the oven door for a cheesecake that's creamy in the centre, or leave it closed if you prefer a drier texture. Let cool in the oven for 2 hours. The cheesecake may get a slight crack on top as it cools.\r\nCombine the reserved soured cream with the 142ml carton, the sugar and lemon juice for the topping. Spread over the cheesecake right to the edges. Cover loosely with foil and refrigerate for at least 8 hours or overnight.\r\nRun a round-bladed knife around the sides of the tin to loosen any stuck edges. Unlock the side, slide the cheesecake off the bottom of the tin onto a plate, then slide the parchment paper out from underneath.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/swttys1511385853.jpg",
            "strTags": "Desert,Dairy,Pudding,Cake,Breakfast",
            "strYoutube": "https://www.youtube.com/watch?v=tspdJ6hxqnc",
            "strIngredient1": "Butter",
            "strIngredient2": "Sour Cream",
            "strIngredient3": "Sugar",
            "strIngredient4": "Cream Cheese",
            "strIngredient5": "Caster Sugar",
            "strIngredient6": "Plain Flour",
            "strIngredient7": "Lemon Juice",
            "strIngredient8": "Eggs",
            "strIngredient9": "Sour Cream",
            "strIngredient10": "Sour Cream",
            "strIngredient11": "Caster Sugar",
            "strIngredient12": "Lemon Juice",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "85g",
            "strMeasure2": "140g",
            "strMeasure3": "1tbsp",
            "strMeasure4": "900g",
            "strMeasure5": "250g",
            "strMeasure6": "3 tbs",
            "strMeasure7": "1 ½ teaspoons",
            "strMeasure8": "3 Large",
            "strMeasure9": "250ml",
            "strMeasure10": "150ml",
            "strMeasure11": "1 tbsp",
            "strMeasure12": "2 tsp",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.bbcgoodfood.com/recipes/2869/new-york-cheesecake",
            "dateModified": null
            },
            dessert10: {
            "idMeal": "52794",
            "strMeal": "Vegan Chocolate Cake",
            "strDrinkAlternate": null,
            "strCategory": "Vegan",
            "strArea": "American",
            "strInstructions": "Simply mix all dry ingredients with wet ingredients and blend altogether. Bake for 45 min on 180 degrees. Decorate with some melted vegan chocolate ",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/qxutws1486978099.jpg",
            "strTags": "Vegan,Chocolate,Cake",
            "strYoutube": "https://www.youtube.com/watch?v=C3pAgB7pync",
            "strIngredient1": "self raising flour",
            "strIngredient2": "coco sugar",
            "strIngredient3": "cacao",
            "strIngredient4": "baking powder",
            "strIngredient5": "flax eggs",
            "strIngredient6": "almond milk",
            "strIngredient7": "vanilla",
            "strIngredient8": "water",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "1 1/4 cup",
            "strMeasure2": "1/2 cup",
            "strMeasure3": "1/3 cup raw",
            "strMeasure4": "1 tsp",
            "strMeasure5": "2",
            "strMeasure6": "1/2 cup",
            "strMeasure7": "1 tsp",
            "strMeasure8": "1/2 cup boiling",
            "strMeasure9": "",
            "strMeasure10": "",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "",
            "dateModified": null
            },
            dessert11: {
            "idMeal": "52970",
            "strMeal": "Tunisian Orange Cake",
            "strDrinkAlternate": null,
            "strCategory": "Dessert",
            "strArea": "Tunisian",
            "strInstructions": "Preheat oven to 190 C / Gas 5. Grease a 23cm round springform tin.\r\nCut off the hard bits from the top and bottom of the orange. Slice the orange and remove all seeds. Puree the orange with its peel in a food processor. Add one third of the sugar and the olive oil and continue to mix until well combined.\r\nSieve together flour and baking powder.\r\nBeat the eggs and the remaining sugar with an electric hand mixer for at least five minutes until very fluffy. Fold in half of the flour mixture, then the orange and the vanilla, then fold in the remaining flour. Mix well but not for too long.\r\nPour cake mixture into prepared tin and smooth out. Bake in preheated oven for 20 minutes. Reduce the oven temperature to 160 C / Gas 2 and bake again for 30 minutes Bake until the cake is golden brown and a skewer comes out clean. Cool on a wire cake rack.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/y4jpgq1560459207.jpg",
            "strTags": null,
            "strYoutube": "https://www.youtube.com/watch?v=rCUxg866Ea4",
            "strIngredient1": "Orange",
            "strIngredient2": "Caster Sugar",
            "strIngredient3": "Olive Oil",
            "strIngredient4": "Flour",
            "strIngredient5": "Baking Powder",
            "strIngredient6": "Eggs",
            "strIngredient7": "Vanilla Extract",
            "strIngredient8": "",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "1 large",
            "strMeasure2": "300g",
            "strMeasure3": "75 ml ",
            "strMeasure4": "280g",
            "strMeasure5": "1 tbs",
            "strMeasure6": "4 large",
            "strMeasure7": "2 tsp",
            "strMeasure8": " ",
            "strMeasure9": " ",
            "strMeasure10": " ",
            "strMeasure11": " ",
            "strMeasure12": " ",
            "strMeasure13": " ",
            "strMeasure14": " ",
            "strMeasure15": " ",
            "strMeasure16": " ",
            "strMeasure17": " ",
            "strMeasure18": " ",
            "strMeasure19": " ",
            "strMeasure20": " ",
            "strSource": "http://allrecipes.co.uk/recipe/16067/tunisian-orange-cake.aspx",
            "dateModified": null
            },
            dessert12: {
            "idMeal": "52833",
            "strMeal": "Salted Caramel Cheescake",
            "strDrinkAlternate": null,
            "strCategory": "Dessert",
            "strArea": "American",
            "strInstructions": "1) Blitz the biscuits and the pretzels in a food processor and mix the biscuits with the melted butter. Spread on the bottom of an 8″/20cm Deep Springform Tin and press down firmly. Leave to set in the fridge whilst you make the rest!\r\n\r\n2) Using an electric mixer, I use my KitchenAid with the whisk attachment, whisk together the cream cheese, vanilla, and icing sugar until smooth and then add the caramel and whisk again until smooth and lump free – this could take a couple of minutes, I whisk it at half speed so not too quick or slow!\r\n\r\n3) Pour in the double cream & Salt flakes and continue to whisk for a couple of minutes until its very thick and mousse like (I mix it on a medium speed, level 6/10) – Now this could take up to 5 minutes depending on your mixer, but you seriously have to stick at it – it will hold itself completely when finished mixing (like a meringue does!) If you don’t mix it enough it will not set well enough, but don’t get impatient and whisk it really quick because that’ll make it split! Spread over the biscuit base and leave to set in the fridge overnight.\r\n\r\n4) Remove the Cheesecake from the tin carefully and decorate the cheesecake – I drizzled over some of the spare caramel, and then some Toffee Popcorn and more Pretzels!",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/xqrwyr1511133646.jpg",
            "strTags": null,
            "strYoutube": "https://www.youtube.com/watch?v=q5dQp3qpmI4",
            "strIngredient1": "Digestive Biscuits",
            "strIngredient2": "Pretzels",
            "strIngredient3": "Butter",
            "strIngredient4": "Cream Cheese",
            "strIngredient5": "Vanilla Extract",
            "strIngredient6": "Icing Sugar",
            "strIngredient7": "Caramel",
            "strIngredient8": "Sea Salt",
            "strIngredient9": "Double Cream",
            "strIngredient10": "Caramel Sauce",
            "strIngredient11": "Toffee Popcorn",
            "strIngredient12": "Pretzels",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "250g",
            "strMeasure2": "75g",
            "strMeasure3": "135g",
            "strMeasure4": "450g",
            "strMeasure5": "1tsp",
            "strMeasure6": "100g ",
            "strMeasure7": "150g",
            "strMeasure8": "1tsp",
            "strMeasure9": "300ml ",
            "strMeasure10": "drizzle",
            "strMeasure11": "Top",
            "strMeasure12": "Top",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "http://www.janespatisserie.com/2015/11/09/no-bake-salted-caramel-cheesecake/",
            "dateModified": null
            },
}

export default dessert;