const meat = {
    meat1: {
        "idMeal": "52847",
        "strMeal": "Pork Cassoulet",
        "strDrinkAlternate": null,
        "strCategory": "Pork",
        "strArea": "French",
        "strInstructions": "Heat oven to 140C/120C fan/gas 1. Put a large ovenproof pan (with a tight-fitting lid) on a high heat. Add your fat and diced meat, cook for a few mins to seal the edges, giving it a quick stir to cook evenly. Reduce the heat to low, add the sliced onion, whole garlic cloves, carrot and fennel seeds, and cook gently to soften the veg for a few mins.\r\nPour over the red wine vinegar, scraping any meaty bits off the bottom of the pan. Add the stock, tomato purée, and half the rosemary and parsley. Bring to the boil and simmer for 10 mins, then season, cover with a lid and put into the oven for 2 hrs, removing the lid for the final hour of cooking. Stir occasionally and add the beans with 30 mins to go.\r\nRemove the pan from the oven and heat the grill. Scatter the top with the remaining herbs and breadcrumbs, drizzle a little oil over the top, and return to the oven for 5-10 mins, until the breadcrumbs are golden. Serve with crusty bread and green veg.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/wxuvuv1511299147.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=MEdHMTD0VCA",
        "strIngredient1": "Goose Fat",
        "strIngredient2": "Pork",
        "strIngredient3": "Onion",
        "strIngredient4": "Garlic",
        "strIngredient5": "Carrots",
        "strIngredient6": "Fennel Seeds",
        "strIngredient7": "Red Wine Vinegar",
        "strIngredient8": "Vegetable Stock",
        "strIngredient9": "Tomato Puree",
        "strIngredient10": "Rosemary",
        "strIngredient11": "Parsley",
        "strIngredient12": "Haricot Beans",
        "strIngredient13": "Breadcrumbs",
        "strIngredient14": "Oil",
        "strIngredient15": "Bread",
        "strIngredient16": "Broccoli",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "4 tbsp",
        "strMeasure2": "350g",
        "strMeasure3": "1 large",
        "strMeasure4": "10",
        "strMeasure5": "1 thinly sliced",
        "strMeasure6": "1 tsp ",
        "strMeasure7": "2 tblsp ",
        "strMeasure8": "600ml",
        "strMeasure9": "1 tblsp ",
        "strMeasure10": "2 sticks",
        "strMeasure11": "Handful",
        "strMeasure12": "400g",
        "strMeasure13": "2 tblsp ",
        "strMeasure14": "drizzle",
        "strMeasure15": "to serve",
        "strMeasure16": "to serve",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/jacks-pork-cassoulet",
        "dateModified": null
        },
        meat2: {
        "idMeal": "52949",
        "strMeal": "Sweet and Sour Pork",
        "strDrinkAlternate": null,
        "strCategory": "Pork",
        "strArea": "Chinese",
        "strInstructions": "Preparation\r\n1. Crack the egg into a bowl. Separate the egg white and yolk.\r\n\r\nSweet and Sour Pork\r\n2. Slice the pork tenderloin into strips.\r\n\r\n3. Prepare the marinade using a pinch of salt, one teaspoon of starch, two teaspoons of light soy sauce, and an egg white.\r\n\r\n4. Marinade the pork strips for about 20 minutes.\r\n\r\n5. Put the remaining starch in a bowl. Add some water and vinegar to make a starchy sauce.\r\n\r\nSweet and Sour Pork\r\nCooking Instructions\r\n1. Pour the cooking oil into a wok and heat to 190°C (375°F). Add the marinated pork strips and fry them until they turn brown. Remove the cooked pork from the wok and place on a plate.\r\n\r\n2. Leave some oil in the wok. Put the tomato sauce and white sugar into the wok, and heat until the oil and sauce are fully combined.\r\n\r\n3. Add some water to the wok and thoroughly heat the sweet and sour sauce before adding the pork strips to it.\r\n\r\n4. Pour in the starchy sauce. Stir-fry all the ingredients until the pork and sauce are thoroughly mixed together.\r\n\r\n5. Serve on a plate and add some coriander for decoration.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/1529442316.jpg",
        "strTags": "Sweet",
        "strYoutube": "https://www.youtube.com/watch?v=mdaBIhgEAMo",
        "strIngredient1": "Pork",
        "strIngredient2": "Egg",
        "strIngredient3": "Water",
        "strIngredient4": "Salt",
        "strIngredient5": "Sugar",
        "strIngredient6": "Soy Sauce",
        "strIngredient7": "Starch",
        "strIngredient8": "Tomato Puree",
        "strIngredient9": "Vinegar",
        "strIngredient10": "Coriander",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "200g",
        "strMeasure2": "1",
        "strMeasure3": "Dash",
        "strMeasure4": "1/2 tsp",
        "strMeasure5": "1 tsp ",
        "strMeasure6": "10g",
        "strMeasure7": "10g",
        "strMeasure8": "30g",
        "strMeasure9": "10g",
        "strMeasure10": "Dash",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.chinahighlights.com/travelguide/chinese-food/cooking/sweet-sour-pork.htm",
        "dateModified": null
        },
        meat3: {
        "idMeal": "52828",
        "strMeal": "Vietnamese Grilled Pork (bun-thit-nuong)",
        "strDrinkAlternate": null,
        "strCategory": "Pork",
        "strArea": "Vietnamese",
        "strInstructions": "Slice the uncooked pork thinly, about ⅛\". It helps to slightly freeze it (optional).\r\nMince garlic and shallots. Mix in a bowl with sugar, fish sauce, thick soy sauce, pepper, and oil until sugar dissolves.\r\nMarinate the meat for 1 hour, or overnight for better results.\r\nBake the pork at 375F for 10-15 minutes or until about 80% cooked. Finish cooking by broiling in the oven until a nice golden brown color develops, flipping the pieces midway.\r\nAssemble your bowl with veggies, noodles, and garnish. Many like to mix the whole bowl up and pour the fish sauce on top, but I like to make individual bites and sauce it slowly.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/qqwypw1504642429.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=Q3qcQcENzbU",
        "strIngredient1": "Pork",
        "strIngredient2": "Rice Vermicelli",
        "strIngredient3": "Egg Rolls",
        "strIngredient4": "Challots",
        "strIngredient5": "Garlic",
        "strIngredient6": "Sugar",
        "strIngredient7": "Fish Sauce",
        "strIngredient8": "Soy sauce",
        "strIngredient9": "Pepper",
        "strIngredient10": "Olive Oil",
        "strIngredient11": "Cucumber",
        "strIngredient12": "Mint",
        "strIngredient13": "Peanuts",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "1.5 pounds sliced",
        "strMeasure2": "1 package thin",
        "strMeasure3": "4-6",
        "strMeasure4": "3 tablespoons minced",
        "strMeasure5": "1.5 tablespoons minced garlic",
        "strMeasure6": "¼ cup",
        "strMeasure7": "1 tablespoon",
        "strMeasure8": "½ tablespoon thick",
        "strMeasure9": "½ tablespoon",
        "strMeasure10": "3 tablespoons",
        "strMeasure11": "Sliced",
        "strMeasure12": "Leaves",
        "strMeasure13": "Crushed",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "http://www.hungryhuy.com/bun-thit-nuong-recipe-vietnamese-grilled-bbq-pork-with-rice-vermicelli-vegetables/",
        "dateModified": null
        },
    meat4: {
        "idMeal": "52836",
        "strMeal": "Seafood fideuà",
        "strDrinkAlternate": null,
        "strCategory": "Seafood",
        "strArea": "Spanish",
        "strInstructions": "Boil the kettle. Empty the mussels into a colander and run under cold water. Throw away any with broken shells. Pick through the shells, tapping each one on the side of the sink – they should be closed or should slowly close when tapped – if they stay open, throw them away. If any of the shells still have barnacles or stringy beards attached, pull them off with a cutlery knife and rinse the shells well. Keep in the colander, covered with a cold, damp cloth, until you’re ready to cook. Peel the prawn shells on the body section only – leave the heads and tails intact. Score down the backs and pull out any gritty entrails. Chill until you’re ready to cook.\r\nPut the saffron in a small cup, cover with 50ml kettle-hot water and set aside for 10 mins. If using vermicelli, put in a bowl and crush to little pieces (about 1cm long) with your hands.\r\nHeat the oil in a large frying pan with at least a 3cm lip, or a 40cm paella pan. Add the onion and stir around the pan for 5 mins until soft. Add the garlic and cook for 1 min more, then tip in the vermicelli and cook for 5 mins, stirring from time to time, until the vermicelli is toasted brown. Stir in the paprika.\r\nKeeping the heat moderate, stir through the monkfish, squid and saffron with its water, seasoning well. Spread the ingredients out in an even layer, then pour over the hot stock and scatter the tomatoes on top. Bring to a simmer, then cover the whole dish with a tight-fitting lid (or foil). Turn the heat to medium and cook for 6 mins.\r\nUncover and stir to incorporate the dry top layer of pasta. Push the mussels into the pasta so the hinges are buried in the bottom of the dish, and they stand straight up. Arrange the prawns on top, cover tightly and cook for another 6 mins or until the mussels are open, the prawns are pink and the pasta is cooked through. Leave to simmer for another 2-3 mins to cook off most of the remaining liquid (leave a little in the pan to prevent the pasta from sticking together). Allow to sit for 2-3 mins, then squeeze over the lemon juice and arrange the wedges on top. Scatter with parsley before serving.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/wqqvyq1511179730.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=itsFEc8W468",
        "strIngredient1": "Mussels",
        "strIngredient2": "Prawns",
        "strIngredient3": "Saffron",
        "strIngredient4": "Vermicelli",
        "strIngredient5": "Olive Oil",
        "strIngredient6": "Onions",
        "strIngredient7": "Garlic",
        "strIngredient8": "Paprika",
        "strIngredient9": "Monkfish",
        "strIngredient10": "Baby Squid",
        "strIngredient11": "Fish Stock",
        "strIngredient12": "Tomatoes",
        "strIngredient13": "Lemon",
        "strIngredient14": "Parsley",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "400g",
        "strMeasure2": "8",
        "strMeasure3": "2 pinches",
        "strMeasure4": "350g",
        "strMeasure5": "5 tblsp ",
        "strMeasure6": "1 large",
        "strMeasure7": "3 cloves",
        "strMeasure8": "2 tbs",
        "strMeasure9": "1 tail",
        "strMeasure10": "4",
        "strMeasure11": "650ml",
        "strMeasure12": "2 large",
        "strMeasure13": "Juice of 1",
        "strMeasure14": "Topping",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/seafood-fideua-paella",
        "dateModified": null
        },
        meat5: {
            "idMeal": "52968",
            "strMeal": "Mbuzi Choma (Roasted Goat)",
            "strDrinkAlternate": null,
            "strCategory": "Goat",
            "strArea": "Kenyan",
            "strInstructions": "1. Steps for the Meat: \r\n Roast meat over medium heat for 50 minutes and salt it as you turn it.\r\n\r\n2. Steps for Ugali:\r\nBring the water and salt to a boil in a heavy-bottomed saucepan. Stir in the cornmeal slowly, letting it fall through the fingers of your hand.\r\n\r\n3. Reduce heat to medium-low and continue stirring regularly, smashing any lumps with a spoon, until the mush pulls away from the sides of the pot and becomes very thick, about 10 minutes.\r\n\r\n4.Remove from heat and allow to cool.\r\n\r\n5. Place the ugali into a large serving bowl. Wet your hands with water, form a ball and serve.\r\n\r\n6. Steps for Kachumbari: Mix the tomatoes, onions, chili and coriander leaves in a bowl.\r\n\r\n7. Serve and enjoy!\r\n\r\n",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/cuio7s1555492979.jpg",
            "strTags": "BBQ,Meat",
            "strYoutube": "",
            "strIngredient1": "Goat Meat",
            "strIngredient2": "Corn Flour",
            "strIngredient3": "Tomatoes",
            "strIngredient4": "Salt",
            "strIngredient5": "Onion",
            "strIngredient6": "Green Chilli",
            "strIngredient7": "Coriander Leaves",
            "strIngredient8": "",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "1 kg",
            "strMeasure2": "1 kg",
            "strMeasure3": "2",
            "strMeasure4": "Pinch",
            "strMeasure5": "1",
            "strMeasure6": "1",
            "strMeasure7": "1  bunch",
            "strMeasure8": " ",
            "strMeasure9": " ",
            "strMeasure10": " ",
            "strMeasure11": " ",
            "strMeasure12": " ",
            "strMeasure13": " ",
            "strMeasure14": " ",
            "strMeasure15": " ",
            "strMeasure16": " ",
            "strMeasure17": " ",
            "strMeasure18": " ",
            "strMeasure19": " ",
            "strMeasure20": " ",
            "strSource": "",
            "dateModified": null
            },
        meat6: {
            "idMeal": "52802",
            "strMeal": "Fish pie",
            "strDrinkAlternate": null,
            "strCategory": "Seafood",
            "strArea": "British",
            "strInstructions": "01.Put the potatoes in a large pan of cold salted water and bring to the boil. Lower the heat, cover, then simmer gently for 15 minutes until tender. Drain, then return to the pan over a low heat for 30 seconds to drive off any excess water. Mash with 1 tbsp olive oil, then season.\r\n02.Meanwhile put the milk in a large sauté pan, add the fish and bring to the boil. Remove from the heat, cover and stand for 3 minutes. Remove the fish (reserving the milk) and pat dry with kitchen paper, then gently flake into an ovenproof dish, discarding the skin and any bones.\r\n03.Heat the remaining oil in a pan, stir in the flour and cook for 30 seconds. Gradually stir in 200-250ml of the reserved milk (discard the rest). Grate in nutmeg, season, then bubble until thick. Stir in the cream.\r\n04.Preheat the oven to 190°C/fan170°C/gas 5. Grate the artichokes and add to the dish with the leek, prawns and herbs. Stir the lemon zest and juice into the sauce, then pour over. Mix gently with a wooden spoon.\r\n05.Spoon the mash onto the fish mixture, then use a fork to make peaks, which will crisp and brown as it cooks. Sprinkle over the cheese, then bake for 35-40 minutes until golden and bubbling. Serve with wilted greens.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg",
            "strTags": "Fish,Pie,Breakfast,Baking",
            "strYoutube": "https://www.youtube.com/watch?v=2sX4fCgg-UI",
            "strIngredient1": "Floury Potatoes",
            "strIngredient2": "Olive Oil",
            "strIngredient3": "Semi-skimmed Milk",
            "strIngredient4": "White Fish Fillets",
            "strIngredient5": "Plain flour",
            "strIngredient6": "Nutmeg",
            "strIngredient7": "Double Cream",
            "strIngredient8": "Jerusalem Artichokes",
            "strIngredient9": "Leek",
            "strIngredient10": "Prawns",
            "strIngredient11": "Parsley",
            "strIngredient12": "Dill",
            "strIngredient13": "Lemon",
            "strIngredient14": "Gruyère",
            "strIngredient15": "Lemon",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "900g",
            "strMeasure2": "2 tbsp",
            "strMeasure3": "600ml",
            "strMeasure4": "800g",
            "strMeasure5": "1 tbsp",
            "strMeasure6": "Grating",
            "strMeasure7": "3 tbsp",
            "strMeasure8": "200g",
            "strMeasure9": "1 finely sliced",
            "strMeasure10": "200g peeled raw",
            "strMeasure11": "Large handful",
            "strMeasure12": "Handful",
            "strMeasure13": "Grated zest of 1",
            "strMeasure14": "25g grated",
            "strMeasure15": "Juice of 1",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "",
            "dateModified": null
            },
            meat7: {
            "idMeal": "52882",
            "strMeal": "Three Fish Pie",
            "strDrinkAlternate": null,
            "strCategory": "Seafood",
            "strArea": "British",
            "strInstructions": "Preheat the oven to 200C/400F/Gas 6 (180C fan).\r\nPut the potatoes into a saucepan of cold salted water. Bring up to the boil and simmer until completely tender. Drain well and then mash with the butter and milk. Add pepper and taste to check the seasoning. Add salt and more pepper if necessary.\r\nFor the fish filling, melt the butter in a saucepan, add the leeks and stir over the heat. Cover with a lid and simmer gently for 10 minutes, or until soft. Measure the flour into a small bowl. Add the wine and whisk together until smooth.\r\nAdd the milk to the leeks, bring to the boil and then add the wine mixture. Stir briskly until thickened. Season and add the parsley and fish. Stir over the heat for two minutes, then spoon into an ovenproof casserole. Scatter over the eggs. Allow to cool until firm.\r\nSpoon the mashed potatoes over the fish mixture and mark with a fork. Sprinkle with cheese.\r\nBake for 30-40 minutes, or until lightly golden-brown on top and bubbling around the edges.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/spswqs1511558697.jpg",
            "strTags": "Fish,Seafood,Dairy,Pie",
            "strYoutube": "https://www.youtube.com/watch?v=Ds1Jb8H5Sg8",
            "strIngredient1": "Potatoes",
            "strIngredient2": "Butter",
            "strIngredient3": "Milk",
            "strIngredient4": "Gruyère",
            "strIngredient5": "Butter",
            "strIngredient6": "Leek",
            "strIngredient7": "Plain Flour",
            "strIngredient8": "White Wine",
            "strIngredient9": "Milk",
            "strIngredient10": "Parsley",
            "strIngredient11": "Salmon",
            "strIngredient12": "Haddock",
            "strIngredient13": "Smoked Haddock",
            "strIngredient14": "Eggs",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "1kg",
            "strMeasure2": "Knob",
            "strMeasure3": "Dash",
            "strMeasure4": "50g",
            "strMeasure5": "75g",
            "strMeasure6": "2 sliced",
            "strMeasure7": "75g",
            "strMeasure8": "150ml",
            "strMeasure9": "568ml",
            "strMeasure10": "2 tbs chopped",
            "strMeasure11": "250g",
            "strMeasure12": "250g",
            "strMeasure13": "250g",
            "strMeasure14": "6",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.bbc.co.uk/food/recipes/three_fish_pie_58875",
            "dateModified": null
            },
            meat8: {
            "idMeal": "52944",
            "strMeal": "Escovitch Fish",
            "strDrinkAlternate": null,
            "strCategory": "Seafood",
            "strArea": "Jamaican",
            "strInstructions": "Rinse fish; rub with lemon or lime, seasoned with salt and pepper or use your favorite seasoning. I used creole seasoning. Set aside or place in the oven to keep it warm until sauce is ready.\r\n\r\nIn large skillet heat oil over medium heat, until hot, add the fish, cook each side- for about 5-7 minutes until cooked through and crispy on both sides. Remove fish and set aside. Drain oil and leave about 2-3 tablespoons of oil\r\nAdd, bay leave, garlic and ginger, stir-fry for about a minute making sure the garlic does not burn\r\nThen add onion, bell peppers, thyme, scotch bonnet, sugar, all spice-continue stirring for about 2-3 minutes. Add vinegar, mix an adjust salt and pepper according to preference. Let it simmer for about 2 more minutes. \r\n\r\nDiscard bay leave, thyme spring and serve over fish with a side of this bammy. You may make the sauce about 2 days in advance.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/1520084413.jpg",
            "strTags": "Seafood,Spicy,Speciality,Easter",
            "strYoutube": "https://www.youtube.com/watch?v=nF6DOtGE6k8",
            "strIngredient1": "Red Snapper",
            "strIngredient2": "Vegetable Oil",
            "strIngredient3": "Garlic",
            "strIngredient4": "Ginger",
            "strIngredient5": "Thyme",
            "strIngredient6": "Bay Leaf",
            "strIngredient7": "Red Pepper",
            "strIngredient8": "Yellow Pepper",
            "strIngredient9": "Onion",
            "strIngredient10": "Carrots",
            "strIngredient11": "Sugar",
            "strIngredient12": "Allspice",
            "strIngredient13": "Worcestershire Sauce",
            "strIngredient14": "Scotch Bonnet",
            "strIngredient15": "Lime",
            "strIngredient16": "Malt Vinegar",
            "strIngredient17": "Pepper",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "2 Pounds",
            "strMeasure2": "1/2 cup ",
            "strMeasure3": "1 clove peeled crushed",
            "strMeasure4": "1/2 tsp",
            "strMeasure5": "2 sprigs",
            "strMeasure6": "1",
            "strMeasure7": "0.5",
            "strMeasure8": "0.5",
            "strMeasure9": "1 sliced",
            "strMeasure10": "1 chopped",
            "strMeasure11": "1 tbs",
            "strMeasure12": "1/2 tsp",
            "strMeasure13": "1 tsp ",
            "strMeasure14": "1",
            "strMeasure15": "1",
            "strMeasure16": "3/4 cup ",
            "strMeasure17": "pinch",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.africanbites.com/jamaican-escovitched-fish/",
            "dateModified": null
            },
            meat9: {
            "idMeal": "52936",
            "strMeal": "Saltfish and Ackee",
            "strDrinkAlternate": null,
            "strCategory": "Seafood",
            "strArea": "Jamaican",
            "strInstructions": "For the saltfish, soak the salt cod overnight, changing the water a couple of times.\r\nDrain, then put the cod in a large pan of fresh water and bring to the boil. Drain again, add fresh water and bring to the boil again.\r\nSimmer for about five minutes, or until cooked through, then drain and flake the fish into large pieces. Discard any skin or bones.\r\nFor the dumplings, mix the flour and suet with a pinch of salt and 250ml/9fl oz water to make a dough.\r\nWrap the mixture in clingfilm and leave in the fridge to rest.\r\nOpen the can of ackee, drain and rinse, then set aside.\r\nHeat a tablespoon of olive oil in a pan and fry the onion until softened but not brown.\r\nAdd the spices, seasoning, pepper sauce and sliced peppers and continue to fry until the peppers are tender.\r\nAdd the chopped tomatoes, then the salt cod and mix together. Lastly stir in the ackee very gently and leave to simmer until ready to serve.\r\nWhen you’re almost ready to eat, heat about 1cm/½in vegetable oil in a frying pan and heat until just smoking.\r\nShape the dumpling mix into plum-size balls and shallow-fry until golden-brown. (CAUTION: hot oil can be dangerous. Do not leave the pan unattended.)\r\nDrain the dumplings on kitchen paper and serve with the saltfish and ackee.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/vytypy1511883765.jpg",
            "strTags": "Speciality",
            "strYoutube": "https://www.youtube.com/watch?v=nbfNyZbdn2I",
            "strIngredient1": "Salt Cod",
            "strIngredient2": "Ackee",
            "strIngredient3": "Onion",
            "strIngredient4": "Paprika",
            "strIngredient5": "Curry Powder",
            "strIngredient6": "Jerusalem Artichokes",
            "strIngredient7": "Hotsauce",
            "strIngredient8": "Red Pepper",
            "strIngredient9": "Yellow Pepper",
            "strIngredient10": "Tomatoes",
            "strIngredient11": "Salt",
            "strIngredient12": "Pepper",
            "strIngredient13": "Self-raising Flour",
            "strIngredient14": "Suet",
            "strIngredient15": "Salt",
            "strIngredient16": "Olive Oil",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "450g",
            "strMeasure2": "400g",
            "strMeasure3": "1 chopped",
            "strMeasure4": "1 tsp ",
            "strMeasure5": "2 tsp",
            "strMeasure6": "2 tsp",
            "strMeasure7": "1 tsp ",
            "strMeasure8": "1 sliced",
            "strMeasure9": "1 sliced",
            "strMeasure10": "200g",
            "strMeasure11": "to taste",
            "strMeasure12": "to taste",
            "strMeasure13": "250g",
            "strMeasure14": "30g",
            "strMeasure15": "pinch",
            "strMeasure16": "for frying",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.bbc.co.uk/food/recipes/saltfish__ackee_with_64803",
            "dateModified": null
            },
            meat10: {
            "idMeal": "52809",
            "strMeal": "Recheado Masala Fish",
            "strDrinkAlternate": null,
            "strCategory": "Seafood",
            "strArea": "Indian",
            "strInstructions": "Soak all the spices, ginger, garlic, tamarind pulp and kashmiri chilies except oil in vinegar.\r\nAdd sugar and salt.\r\nAlso add turmeric powder.\r\nCombine all nicely and marinate for 35-40 mins.\r\nGrind the mixture until soft and smooth. Add more vinegar if required but ensure the paste has to be thick so add vinegar accordingly. If the masala paste is thin then it would not stick to the fish.\r\nRinse the fish slit from the center and give some incision from the top. You could see the fish below for clarity.\r\nNow stuff the paste into the center and into the incision. Coat the entire fish with this paste. Marinate the fish for 30 mins.\r\nPlace oil in a shallow pan, once oil is quite hot shallow fry the stuffed mackerels.\r\nFry until golden brown from both sides\r\nServe the recheado mackerels hot with salad, lime wedges, rice and curry.\r\nNotes\r\n1. Ensure the masala paste is thick else the result won't be good.\r\n2. If you aren't able to find kashmiri chilies then use bedgi chilies or kashmiri red chili powder.\r\n3. You could use white vinegar or coconut vinegar.\r\n4. Any left over paste could be stored in the fridge for future use.\r\n5. Cinnamon could be avoided as it's a strong spice used generally for meat or chicken.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/uwxusv1487344500.jpg",
            "strTags": "Fish,Spicy",
            "strYoutube": "https://www.youtube.com/watch?v=FXtCris37nE",
            "strIngredient1": "Mackerel",
            "strIngredient2": "Red Chili",
            "strIngredient3": "Ginger",
            "strIngredient4": "Garlic",
            "strIngredient5": "Pepper",
            "strIngredient6": "Cumin",
            "strIngredient7": "Turmeric",
            "strIngredient8": "Cinnamon stick",
            "strIngredient9": "Clove",
            "strIngredient10": "Cardamom",
            "strIngredient11": "Sugar",
            "strIngredient12": "Tamarind ball",
            "strIngredient13": "Vinegar",
            "strIngredient14": "Oil",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "4",
            "strMeasure2": "18 dried",
            "strMeasure3": "1 inch",
            "strMeasure4": "8 cloves",
            "strMeasure5": "1.5 tsp",
            "strMeasure6": "1 tsp",
            "strMeasure7": "½ tsp",
            "strMeasure8": "",
            "strMeasure9": "4",
            "strMeasure10": "2",
            "strMeasure11": "1 tbsp",
            "strMeasure12": "2 marble sized",
            "strMeasure13": "2.5 tbsp",
            "strMeasure14": "for frying",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "http://www.flavorsofmumbai.com/fish-recheado-masala-recipe/",
            "dateModified": null
            },
            meat11: {
            "idMeal": "52918",
            "strMeal": "Fish Stew with Rouille",
            "strDrinkAlternate": null,
            "strCategory": "Seafood",
            "strArea": "French",
            "strInstructions": "Twist the heads from the prawns, then peel away the legs and shells, but leave the tails intact. Devein each prawn. Fry the shells in 1 tbsp oil for 5 mins, until dark pink and golden in patches. Add the wine, boil down by two thirds, then pour in the stock. Strain into a jug, discarding the shells.\r\nHeat the rest of the oil in a deep frying pan or casserole. Add the fennel, onion and garlic, season, then cover and gently cook for 10 mins until softened. Meanwhile, peel the potato and cut into 2cm-ish chunks. Put into a pan of cold water, bring to the boil and cook for 5 mins until almost tender. Drain in a colander.\r\nPeel a strip of zest from the orange. Put the zest, star anise, bay and ½ tsp harissa into the pan. Fry gently, uncovered, for 5-10 mins, until the vegetables are soft, sweet and golden.\r\nStir in the tomato purée, cook for 2 mins, then add the tomatoes and stock. Simmer for 10 mins until the sauce thickens slightly. Season to taste. The sauce can be made ahead, then reheated later in the day. Meantime, scrub the mussels or clams and pull away any stringy beards. Any that are open should be tapped sharply on the worktop – if they don’t close after a few seconds, discard them.\r\nReheat the sauce if necessary, then stir the potato, chunks of fish and prawns very gently into the stew. Bring back to the boil, then cover and gently simmer for 3 mins. Scatter the mussels or clams over the stew, then cover and cook for 2 mins more or until the shells have opened wide. Discard any that remain closed. The chunks of fish should flake easily and the prawns should be pink through. Scatter with the thyme leaves.\r\nTo make the quick rouille, stir the rest of the harissa through the mayonnaise. Serve the stew in bowls, topped with spoonfuls of rouille, which will melt into the sauce and enrich it. Have some good bread ready, as you’ll definitely want to mop up the juices.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/vptqpw1511798500.jpg",
            "strTags": "Fish,Seafood,Shellfish",
            "strYoutube": "https://www.youtube.com/watch?v=fp9Lqx2EUco",
            "strIngredient1": "Prawns",
            "strIngredient2": "Olive Oil",
            "strIngredient3": "Dry White Wine",
            "strIngredient4": "Fish Stock",
            "strIngredient5": "Fennel",
            "strIngredient6": "Onion",
            "strIngredient7": "Garlic",
            "strIngredient8": "Potatoes",
            "strIngredient9": "Orange",
            "strIngredient10": "Star Anise",
            "strIngredient11": "Bay Leaf",
            "strIngredient12": "Harissa Spice",
            "strIngredient13": "Tomato Puree",
            "strIngredient14": "Chopped Tomatoes",
            "strIngredient15": "Mussels",
            "strIngredient16": "White Fish",
            "strIngredient17": "Thyme",
            "strIngredient18": "Bread",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "6 large",
            "strMeasure2": "3 tbs",
            "strMeasure3": "150ml",
            "strMeasure4": "200ml",
            "strMeasure5": "1 small finely diced",
            "strMeasure6": "1 small finely diced",
            "strMeasure7": "3 cloves Chopped",
            "strMeasure8": "1 large",
            "strMeasure9": "1",
            "strMeasure10": "1",
            "strMeasure11": "1",
            "strMeasure12": "1 1/2 tsp ",
            "strMeasure13": "2 tbs",
            "strMeasure14": "400g",
            "strMeasure15": "Handful",
            "strMeasure16": "200g",
            "strMeasure17": "2",
            "strMeasure18": "to serve",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.bbcgoodfood.com/recipes/532640/summer-fish-stew-with-rouille",
            "dateModified": null
            },
            meat12: {
            "idMeal": "52819",
            "strMeal": "Cajun spiced fish tacos",
            "strDrinkAlternate": null,
            "strCategory": "Seafood",
            "strArea": "Mexican",
            "strInstructions": "Cooking in a cajun spice and cayenne pepper marinade makes this fish super succulent and flavoursome. Top with a zesty dressing and serve in a tortilla for a quick, fuss-free main that's delightfully summery.\r\n\r\nOn a large plate, mix the cajun spice and cayenne pepper with a little seasoning and use to coat the fish all over.\r\n\r\nHeat a little oil in a frying pan, add in the fish and cook over a medium heat until golden. Reduce the heat and continue frying until the fish is cooked through, about 10 minutes. Cook in batches if you don’t have enough room in the pan.\r\n\r\nMeanwhile, prepare the dressing by combining all the ingredients with a little seasoning.\r\nSoften the tortillas by heating in the microwave for 5-10 seconds. Pile high with the avocado, lettuce and spring onion, add a spoonful of salsa, top with large flakes of fish and drizzle over the dressing.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg",
            "strTags": "Spicy,Fish",
            "strYoutube": "https://www.youtube.com/watch?v=N4EdUt0Ou48",
            "strIngredient1": "cajun",
            "strIngredient2": "cayenne pepper",
            "strIngredient3": "white fish",
            "strIngredient4": "vegetable oil",
            "strIngredient5": "flour tortilla",
            "strIngredient6": "avocado",
            "strIngredient7": "little gem lettuce",
            "strIngredient8": "spring onion",
            "strIngredient9": "salsa",
            "strIngredient10": "sour cream",
            "strIngredient11": "lemon",
            "strIngredient12": "garlic",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "2 tbsp",
            "strMeasure2": "1 tsp",
            "strMeasure3": "4 fillets",
            "strMeasure4": "1 tsp",
            "strMeasure5": "8",
            "strMeasure6": "1 sliced",
            "strMeasure7": "2 shredded",
            "strMeasure8": "4 shredded",
            "strMeasure9": "1 x 300ml",
            "strMeasure10": "1 pot",
            "strMeasure11": "1",
            "strMeasure12": "1 clove finely chopped",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://realfood.tesco.com/recipes/cajun-spiced-fish-tacos.html",
            "dateModified": null
            }
}

export default meat;