const pasta = {
    pasta1: {
    "idMeal": "52821",
    "strMeal": "Laksa King Prawn Noodles",
    "strDrinkAlternate": null,
    "strCategory": "Seafood",
    "strArea": "Malaysian",
    "strInstructions": "Heat the oil in a medium saucepan and add the chilli. Cook for 1 min, then add the curry paste, stir and cook for 1 min more. Dissolve the stock cube in a large jug in 700ml boiling water, then pour into the pan and stir to combine. Tip in the coconut milk and bring to the boil.\r\nAdd the fish sauce and a little seasoning. Toss in the noodles and cook for a further 3-4 mins until softening. Squeeze in the lime juice, add the prawns and cook through until warm, about 2-3 mins. Scatter over some of the coriander.\r\nServe in bowls with the remaining coriander and lime wedges on top for squeezing over.",
    "strMealThumb": "https://www.themealdb.com/images/media/meals/rvypwy1503069308.jpg",
    "strTags": "Shellfish,Seafood",
    "strYoutube": "https://www.youtube.com/watch?v=OcarztU8cYo",
    "strIngredient1": "Olive Oil",
    "strIngredient2": "red chili",
    "strIngredient3": "Thai red curry paste",
    "strIngredient4": "vegetable stock cube",
    "strIngredient5": "coconut milk",
    "strIngredient6": "fish sauce",
    "strIngredient7": "rice noodles",
    "strIngredient8": "lime",
    "strIngredient9": "king prawns",
    "strIngredient10": "coriander",
    "strIngredient11": "",
    "strIngredient12": "",
    "strIngredient13": "",
    "strIngredient14": "",
    "strIngredient15": "",
    "strIngredient16": "",
    "strIngredient17": "",
    "strIngredient18": "",
    "strIngredient19": "",
    "strIngredient20": "",
    "strMeasure1": "1 tbsp",
    "strMeasure2": "1 finely sliced",
    "strMeasure3": "2 ½ tbsp",
    "strMeasure4": "1",
    "strMeasure5": "400ml can",
    "strMeasure6": "2 tsp",
    "strMeasure7": "100g",
    "strMeasure8": "2 juice of 1, the other halved",
    "strMeasure9": "150g",
    "strMeasure10": "½ small pack",
    "strMeasure11": "",
    "strMeasure12": "",
    "strMeasure13": "",
    "strMeasure14": "",
    "strMeasure15": "",
    "strMeasure16": "",
    "strMeasure17": "",
    "strMeasure18": "",
    "strMeasure19": "",
    "strMeasure20": "",
    "strSource": "https://www.bbcgoodfood.com/recipes/prawn-laksa-curry-bowl",
    "dateModified": null
    },
    pasta2: {
        "idMeal": "52777",
        "strMeal": "Mediterranean Pasta Salad",
        "strDrinkAlternate": null,
        "strCategory": "Seafood",
        "strArea": "Italian",
        "strInstructions": "Bring a large saucepan of salted water to the boil\r\nAdd the pasta, stir once and cook for about 10 minutes or as directed on the packet.\r\nMeanwhile, wash the tomatoes and cut into quarters. Slice the olives. Wash the basil.\r\nPut the tomatoes into a salad bowl and tear the basil leaves over them. Add a tablespoon of olive oil and mix.\r\nWhen the pasta is ready, drain into a colander and run cold water over it to cool it quickly.\r\nToss the pasta into the salad bowl with the tomatoes and basil.\r\nAdd the sliced olives, drained mozzarella balls, and chunks of tuna. Mix well and let the salad rest for at least half an hour to allow the flavours to mingle.\r\nSprinkle the pasta with a generous grind of black pepper and drizzle with the remaining olive oil just before serving.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
        "strTags": "Pasta,Baking",
        "strYoutube": "https://www.youtube.com/watch?v=e52IL8zYmaE",
        "strIngredient1": "mozzarella balls",
        "strIngredient2": "baby plum tomatoes",
        "strIngredient3": "fresh basil",
        "strIngredient4": "farfalle",
        "strIngredient5": "extra virgin olive oil",
        "strIngredient6": "Green Olives",
        "strIngredient7": "tuna",
        "strIngredient8": "salt",
        "strIngredient9": "pepper",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": null,
        "strIngredient17": null,
        "strIngredient18": null,
        "strIngredient19": null,
        "strIngredient20": null,
        "strMeasure1": "200 g",
        "strMeasure2": "250 g",
        "strMeasure3": "1  bunch",
        "strMeasure4": "350 g",
        "strMeasure5": "3  tablespoons",
        "strMeasure6": "40 g",
        "strMeasure7": "200 g",
        "strMeasure8": "to taste",
        "strMeasure9": "to taste",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": null,
        "strMeasure17": null,
        "strMeasure18": null,
        "strMeasure19": null,
        "strMeasure20": null,
        "strSource": "https://thelemonsqueezy.com/recipe/mediterranean-pasta-salad/",
        "dateModified": null
        },
        pasta3: {
            "idMeal": "52770",
            "strMeal": "Spaghetti Bolognese",
            "strDrinkAlternate": null,
            "strCategory": "Beef",
            "strArea": "Italian",
            "strInstructions": "Put the onion and oil in a large pan and fry over a fairly high heat for 3-4 mins. Add the garlic and mince and fry until they both brown. Add the mushrooms and herbs, and cook for another couple of mins.\r\n\r\nStir in the tomatoes, beef stock, tomato ketchup or purée, Worcestershire sauce and seasoning. Bring to the boil, then reduce the heat, cover and simmer, stirring occasionally, for 30 mins.\r\n\r\nMeanwhile, cook the spaghetti in a large pan of boiling, salted water, according to packet instructions. Drain well, run hot water through it, put it back in the pan and add a dash of olive oil, if you like, then stir in the meat sauce. Serve in hot bowls and hand round Parmesan cheese, for sprinkling on top.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
            "strTags": "Pasta,Meat",
            "strYoutube": "https://www.youtube.com/watch?v=-gF8d-fitkU",
            "strIngredient1": "onions",
            "strIngredient2": "olive oil",
            "strIngredient3": "garlic",
            "strIngredient4": "lean minced beef",
            "strIngredient5": "mushrooms",
            "strIngredient6": "dried oregano",
            "strIngredient7": "tomatoes",
            "strIngredient8": "hot beef stock",
            "strIngredient9": "tomato puree",
            "strIngredient10": "worcestershire sauce",
            "strIngredient11": "spaghetti",
            "strIngredient12": "parmesan",
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strIngredient16": null,
            "strIngredient17": null,
            "strIngredient18": null,
            "strIngredient19": null,
            "strIngredient20": null,
            "strMeasure1": "2",
            "strMeasure2": "1tbsp",
            "strMeasure3": "1 clove",
            "strMeasure4": "500g",
            "strMeasure5": "90g",
            "strMeasure6": "1tsp",
            "strMeasure7": "400g can",
            "strMeasure8": "300ml",
            "strMeasure9": "1tbsp",
            "strMeasure10": "1tbsp",
            "strMeasure11": "350g",
            "strMeasure12": "Topping",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": null,
            "strMeasure17": null,
            "strMeasure18": null,
            "strMeasure19": null,
            "strMeasure20": null,
            "strSource": null,
            "dateModified": null
            },
        pasta4: {
            "idMeal": "52982",
            "strMeal": "Spaghetti alla Carbonara",
            "strDrinkAlternate": null,
            "strCategory": "Pasta",
            "strArea": "Italian",
            "strInstructions": "Per preparare gli spaghetti alla carbonara cominciate mettendo sul fuoco una pentola con l’acqua salata per cuocere la pasta. Nel frattempo eliminate la cotenna dal guanciale  e tagliatelo prima a fette e poi a striscioline spesse circa 1cm . La cotenna avanzata potrà essere riutilizzata per insaporire altre preparazioni. Versate i pezzetti in una padella antiaderente e rosolate per circa 15 minuti a fiamma media, fate attenzione a non bruciarlo altrimenti rilascerà un aroma troppo forte.\r\n\r\nNel frattempo tuffate gli spaghetti nell’acqua bollente e cuoceteli per il tempo indicato sulla confezione. Intanto versate i tuorli in una ciotola, aggiungete anche la maggior parte del pecorino previsto dalla ricetta la parte restante servirà per guarnire la pasta.\r\n\r\nInsaporite con il pepe nero, amalgamate tutto con una frusta a mano. Aggiungete un cucchiaio di acqua di cottura per diluire il composto e mescolate.\r\n\r\n\r\nIntanto il guanciale sarà giunto a cottura, spegnete il fuoco e tenetelo da parte. Scolate la pasta al dente direttamente nel tegame con il guanciale e saltatela brevemente per insaporirla. Togliete dal fuoco e versate il composto di uova e pecorino nel tegame, saltate la pasta per amalgamare\r\n\r\n\r\ne se dovesse risultare troppo asciutta potete aggiungere poca acqua di cottura. Servite subito gli spaghetti alla carbonara insaporendoli con il pecorino avanzato e il pepe nero macinato.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg",
            "strTags": "Pasta,BBQ,Breakfast",
            "strYoutube": "https://www.youtube.com/watch?v=_T6jkRvhlkk",
            "strIngredient1": "Spaghetti",
            "strIngredient2": "Egg Yolks",
            "strIngredient3": "Salt",
            "strIngredient4": "Bacon",
            "strIngredient5": "Pecorino",
            "strIngredient6": "Black Pepper",
            "strIngredient7": "",
            "strIngredient8": "",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "320g",
            "strMeasure2": "6",
            "strMeasure3": "As required",
            "strMeasure4": "150g",
            "strMeasure5": "50g",
            "strMeasure6": "As required",
            "strMeasure7": " ",
            "strMeasure8": " ",
            "strMeasure9": " ",
            "strMeasure10": " ",
            "strMeasure11": " ",
            "strMeasure12": " ",
            "strMeasure13": " ",
            "strMeasure14": " ",
            "strMeasure15": " ",
            "strMeasure16": " ",
            "strMeasure17": " ",
            "strMeasure18": " ",
            "strMeasure19": " ",
            "strMeasure20": " ",
            "strSource": "https://ricette.giallozafferano.it/Spaghetti-alla-Carbonara.html",
            "dateModified": null
            },
        pasta5: {
            "idMeal": "52775",
            "strMeal": "Vegan Lasagna",
            "strDrinkAlternate": null,
            "strCategory": "Vegan",
            "strArea": "Italian",
            "strInstructions": "1) Preheat oven to 180 degrees celcius. \r\n2) Boil vegetables for 5-7 minutes, until soft. Add lentils and bring to a gentle simmer, adding a stock cube if desired. Continue cooking and stirring until the lentils are soft, which should take about 20 minutes. \r\n3) Blanch spinach leaves for a few minutes in a pan, before removing and setting aside. \r\n4) Top up the pan with water and cook the lasagne sheets. When cooked, drain and set aside.\r\n5) To make the sauce, melt the butter and add the flour, then gradually add the soya milk along with the mustard and the vinegar. Cook and stir until smooth and then assemble the lasagne as desired in a baking dish. \r\n6) Bake in the preheated oven for about 25 minutes.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/rvxxuy1468312893.jpg",
            "strTags": "Vegan,Pasta",
            "strYoutube": "https://www.youtube.com/watch?v=VU8cXvlGbvc",
            "strIngredient1": "green red lentils",
            "strIngredient2": "carrot",
            "strIngredient3": "onion",
            "strIngredient4": "zucchini",
            "strIngredient5": "coriander",
            "strIngredient6": "spinach",
            "strIngredient7": "lasagne sheets",
            "strIngredient8": "vegan butter",
            "strIngredient9": "flour",
            "strIngredient10": "soya milk",
            "strIngredient11": "mustard",
            "strIngredient12": "vinegar",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": null,
            "strIngredient17": null,
            "strIngredient18": null,
            "strIngredient19": null,
            "strIngredient20": null,
            "strMeasure1": "1 cups",
            "strMeasure2": "1",
            "strMeasure3": "1",
            "strMeasure4": "1 small",
            "strMeasure5": "sprinking",
            "strMeasure6": "150g",
            "strMeasure7": "10",
            "strMeasure8": "35g",
            "strMeasure9": "4 tablespoons",
            "strMeasure10": "300ml",
            "strMeasure11": "1.5 teaspoons",
            "strMeasure12": "1 teaspoon",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": null,
            "strMeasure17": null,
            "strMeasure18": null,
            "strMeasure19": null,
            "strMeasure20": null,
            "strSource": null,
            "dateModified": null
            },
            pasta6: {
            "idMeal": "52771",
            "strMeal": "Spicy Arrabiata Penne",
            "strDrinkAlternate": null,
            "strCategory": "Vegetarian",
            "strArea": "Italian",
            "strInstructions": "Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
            "strTags": "Pasta,Curry",
            "strYoutube": "https://www.youtube.com/watch?v=1IszT_guI08",
            "strIngredient1": "penne rigate",
            "strIngredient2": "olive oil",
            "strIngredient3": "garlic",
            "strIngredient4": "chopped tomatoes",
            "strIngredient5": "red chile flakes",
            "strIngredient6": "italian seasoning",
            "strIngredient7": "basil",
            "strIngredient8": "Parmigiano-Reggiano",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": null,
            "strIngredient17": null,
            "strIngredient18": null,
            "strIngredient19": null,
            "strIngredient20": null,
            "strMeasure1": "1 pound",
            "strMeasure2": "1/4 cup",
            "strMeasure3": "3 cloves",
            "strMeasure4": "1 tin ",
            "strMeasure5": "1/2 teaspoon",
            "strMeasure6": "1/2 teaspoon",
            "strMeasure7": "6 leaves",
            "strMeasure8": "spinkling",
            "strMeasure9": "",
            "strMeasure10": "",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": null,
            "strMeasure17": null,
            "strMeasure18": null,
            "strMeasure19": null,
            "strMeasure20": null,
            "strSource": null,
            "dateModified": null
                    
            }
}

export default pasta;