const vegetarian = {
    vegetarian1: {
        "idMeal": "52775",
        "strMeal": "Vegan Lasagna",
        "strDrinkAlternate": null,
        "strCategory": "Vegan",
        "strArea": "Italian",
        "strInstructions": "1) Preheat oven to 180 degrees celcius. \r\n2) Boil vegetables for 5-7 minutes, until soft. Add lentils and bring to a gentle simmer, adding a stock cube if desired. Continue cooking and stirring until the lentils are soft, which should take about 20 minutes. \r\n3) Blanch spinach leaves for a few minutes in a pan, before removing and setting aside. \r\n4) Top up the pan with water and cook the lasagne sheets. When cooked, drain and set aside.\r\n5) To make the sauce, melt the butter and add the flour, then gradually add the soya milk along with the mustard and the vinegar. Cook and stir until smooth and then assemble the lasagne as desired in a baking dish. \r\n6) Bake in the preheated oven for about 25 minutes.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/rvxxuy1468312893.jpg",
        "strTags": "Vegan,Pasta",
        "strYoutube": "https://www.youtube.com/watch?v=VU8cXvlGbvc",
        "strIngredient1": "green red lentils",
        "strIngredient2": "carrot",
        "strIngredient3": "onion",
        "strIngredient4": "zucchini",
        "strIngredient5": "coriander",
        "strIngredient6": "spinach",
        "strIngredient7": "lasagne sheets",
        "strIngredient8": "vegan butter",
        "strIngredient9": "flour",
        "strIngredient10": "soya milk",
        "strIngredient11": "mustard",
        "strIngredient12": "vinegar",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": null,
        "strIngredient17": null,
        "strIngredient18": null,
        "strIngredient19": null,
        "strIngredient20": null,
        "strMeasure1": "1 cups",
        "strMeasure2": "1",
        "strMeasure3": "1",
        "strMeasure4": "1 small",
        "strMeasure5": "sprinking",
        "strMeasure6": "150g",
        "strMeasure7": "10",
        "strMeasure8": "35g",
        "strMeasure9": "4 tablespoons",
        "strMeasure10": "300ml",
        "strMeasure11": "1.5 teaspoons",
        "strMeasure12": "1 teaspoon",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": null,
        "strMeasure17": null,
        "strMeasure18": null,
        "strMeasure19": null,
        "strMeasure20": null,
        "strSource": null,
        "dateModified": null
        },
        vegetarian2: {
        "idMeal": "52794",
        "strMeal": "Vegan Chocolate Cake",
        "strDrinkAlternate": null,
        "strCategory": "Vegan",
        "strArea": "American",
        "strInstructions": "Simply mix all dry ingredients with wet ingredients and blend altogether. Bake for 45 min on 180 degrees. Decorate with some melted vegan chocolate ",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/qxutws1486978099.jpg",
        "strTags": "Vegan,Chocolate,Cake",
        "strYoutube": "https://www.youtube.com/watch?v=C3pAgB7pync",
        "strIngredient1": "self raising flour",
        "strIngredient2": "coco sugar",
        "strIngredient3": "cacao",
        "strIngredient4": "baking powder",
        "strIngredient5": "flax eggs",
        "strIngredient6": "almond milk",
        "strIngredient7": "vanilla",
        "strIngredient8": "water",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "1 1/4 cup",
        "strMeasure2": "1/2 cup",
        "strMeasure3": "1/3 cup raw",
        "strMeasure4": "1 tsp",
        "strMeasure5": "2",
        "strMeasure6": "1/2 cup",
        "strMeasure7": "1 tsp",
        "strMeasure8": "1/2 cup boiling",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "",
        "dateModified": null
        },
        vegetarian3: {
            "idMeal": "52867",
            "strMeal": "Vegetarian Chilli",
            "strDrinkAlternate": null,
            "strCategory": "Vegetarian",
            "strArea": "British",
            "strInstructions": "Heat oven to 200C/180C fan/ gas 6. Cook the vegetables in a casserole dish for 15 mins. Tip in the beans and tomatoes, season, and cook for another 10-15 mins until piping hot. Heat the pouch in the microwave on High for 1 min and serve with the chilli.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/wqurxy1511453156.jpg",
            "strTags": "Chilli",
            "strYoutube": "https://www.youtube.com/watch?v=D0bFRVH_EqU",
            "strIngredient1": "Roasted Vegetables",
            "strIngredient2": "Kidney Beans",
            "strIngredient3": "Chopped Tomatoes",
            "strIngredient4": "Mixed Grain",
            "strIngredient5": "",
            "strIngredient6": "",
            "strIngredient7": "",
            "strIngredient8": "",
            "strIngredient9": "",
            "strIngredient10": "",
            "strIngredient11": "",
            "strIngredient12": "",
            "strIngredient13": "",
            "strIngredient14": "",
            "strIngredient15": "",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "400g",
            "strMeasure2": "1 can ",
            "strMeasure3": "1 can ",
            "strMeasure4": "1 Packet",
            "strMeasure5": "",
            "strMeasure6": "",
            "strMeasure7": "",
            "strMeasure8": "",
            "strMeasure9": "",
            "strMeasure10": "",
            "strMeasure11": "",
            "strMeasure12": "",
            "strMeasure13": "",
            "strMeasure14": "",
            "strMeasure15": "",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.bbcgoodfood.com/recipes/veggie-chilli",
            "dateModified": null
            },
            vegetarian4: {
            "idMeal": "52863",
            "strMeal": "Vegetarian Casserole",
            "strDrinkAlternate": null,
            "strCategory": "Vegetarian",
            "strArea": "British",
            "strInstructions": "Heat the oil in a large, heavy-based pan. Add the onions and cook gently for 5 – 10 mins until softened.\r\nAdd the garlic, spices, dried thyme, carrots, celery and peppers and cook for 5 minutes.\r\nAdd the tomatoes, stock, courgettes and fresh thyme and cook for 20 - 25 minutes.\r\nTake out the thyme sprigs. Stir in the lentils and bring back to a simmer. Serve with wild and white basmati rice, mash or quinoa.",
            "strMealThumb": "https://www.themealdb.com/images/media/meals/vptwyt1511450962.jpg",
            "strTags": "Casserole,Vegetarian",
            "strYoutube": "https://www.youtube.com/watch?v=oHmKE9mWtWM",
            "strIngredient1": "Rapeseed Oil",
            "strIngredient2": "Onion",
            "strIngredient3": "Garlic",
            "strIngredient4": "Paprika",
            "strIngredient5": "Cumin",
            "strIngredient6": "Thyme",
            "strIngredient7": "Carrots",
            "strIngredient8": "Celery",
            "strIngredient9": "Red Pepper",
            "strIngredient10": "Yellow Pepper",
            "strIngredient11": "Tomato",
            "strIngredient12": "Vegetable Stock Cube",
            "strIngredient13": "Courgettes",
            "strIngredient14": "Thyme",
            "strIngredient15": "Lentils",
            "strIngredient16": "",
            "strIngredient17": "",
            "strIngredient18": "",
            "strIngredient19": "",
            "strIngredient20": "",
            "strMeasure1": "1",
            "strMeasure2": "1",
            "strMeasure3": "3 cloves",
            "strMeasure4": "1 tsp ",
            "strMeasure5": "½ tsp",
            "strMeasure6": "1 tblsp ",
            "strMeasure7": "3 Medium",
            "strMeasure8": "2 small stalks",
            "strMeasure9": "1",
            "strMeasure10": "1",
            "strMeasure11": "2 x 400g tins",
            "strMeasure12": "250ml",
            "strMeasure13": "2 sliced",
            "strMeasure14": "2 sprigs",
            "strMeasure15": "250g",
            "strMeasure16": "",
            "strMeasure17": "",
            "strMeasure18": "",
            "strMeasure19": "",
            "strMeasure20": "",
            "strSource": "https://www.bbcgoodfood.com/recipes/1993645/vegetarian-casserole",
            "dateModified": null
            }
}

export default vegetarian;